### ISSUE TITLE
PSI Icons broken in PhpStorm 2020.2

### ISSUE THREAD

**Issue by jdreesen** [mallowigi/a-file-icon-idea#100]
I just updated to the new PhpStorm 2020.2 version.

The PSI icons seem broken, only the pink elephant is shown for `.php` files. The PSI icons of this extension are flashing up sometimes while indexing, though.

**Comment by gldrenthe89** [comment]
Please fix this asap. this is almost every update happening now. 
https://github.com/mallowigi/a-file-icon-idea/issues/80 was also the same thing

**Comment by gldrenthe89** [comment]
Maybe there should be a way of getting a older (working version) instead of one that is incomplete

**Comment by mallowigi** [comment]
Fixing it asap. I'm too busy to work on the project but this should be fixed.

**Comment by gldrenthe89** [comment]
Maybe if you have time you can make a smal how-to so i can take a look and help in these type of situations ;-) I have no clue on how to make these project but i can always tty ;-)

**Comment by mallowigi** [comment]
done. You can download the update in the plugin page, or you can wait until jetbrains approves it

**Comment by gldrenthe89** [comment]
Thanks

**Comment by jdreesen** [comment]
JetBrains finally approved the new version and it's working again. Thx a lot for the quick fix! :)
