### ISSUE TITLE
Go build icon looks different than *.go file icon

### ISSUE THREAD

**Issue by MegOBonus** [mallowigi/a-file-icon-idea#102]
Hello. 
I found than `go build` command icon ![image](https://user-images.githubusercontent.com/7015571/89396269-010bed80-d717-11ea-90ef-655deea6c2b9.png) looks different than `*.go` file icon ![image](https://user-images.githubusercontent.com/7015571/89396340-197c0800-d717-11ea-933e-436e0294a7c0.png).

IDE: Goland v2020.2

**Comment by mallowigi** [comment]
Sorry, not gonna change the icons for now.
