### ISSUE TITLE
Indentation/spacing on custom icons

### ISSUE THREAD

**Issue by yackinn** [mallowigi/a-file-icon-idea#103]
I'm using 16px x 16px icons without spacing on the edges.
Added spacing on the edges will only result in overlapping icons aove the file name or smaller icons.

What's the solution to add spacing between the file name and the icon like in the case of the default Material icons?

users.facade.ts and user.models.ts are custom added icons and they don't have spacing between the file icon and the file name.

![Bildschirmfoto 2020-08-17 um 14 49 46](https://user-images.githubusercontent.com/61085055/90398573-f566e200-e099-11ea-9794-79a889615d2f.png)

**Comment by mallowigi** [comment]
Some of the icons have padding, as you have said. They make the icon appear smaller, indeed, but it is not an issue in general, as those icons are simple. But indeed, I see some weird behaviour in your screenshot, as if the icon "suck up" the text. I'll investigate.
