### ISSUE TITLE
Icon is missing for Kotlin in Tools menu

### ISSUE THREAD

**Issue by cueo** [mallowigi/a-file-icon-idea#107]
Screenshot of the tools menu:
<img width="245" alt="Screenshot 2020-09-16 at 11 25 33 PM" src="https://user-images.githubusercontent.com/13873846/93374550-7b7e7000-f874-11ea-83c0-4886f2f9971d.png">

**Comment by mallowigi** [comment]
Yes, this is a known issue in which i couldn't find a fix. There's an action "Refresh Icon" on the menu though, that hopefully fixes this problem. Try running it to see if it solves the problem.
