### ISSUE TITLE
Add Protocol Buffer (Protobuf) Icon

### ISSUE THREAD

**Issue by liurui39660** [mallowigi/a-file-icon-idea#108]
The icon for the protobuf files (`*.proto`) on my machine is a square with color #4f8890 and a black letter `P` in it. I believe this means protobuf does not have an icon in this plugin, so the IDE uses its default one. Please consider adding it. And below are two of my suggestions (found from web).

The one used by google ↓
![](https://miro.medium.com/max/414/0*7TN4kUdUQIxv0IUM.png)

The logo of another plugin [Protobuf Support](https://plugins.jetbrains.com/plugin/8277-protobuf-support) ↓
![](https://plugins.jetbrains.com/files/8277/59364/icon/pluginIcon.svg)

**Comment by mallowigi** [comment]
done
