### ISSUE TITLE
Force IDE To Reload / Rerender The Icons

### ISSUE THREAD

**Issue by the-wondersmith** [mallowigi/a-file-icon-idea#109]
> Haven't found the fix for this issue unfortunately, but I found a workaround by adding a button that will manually reload the icons, therefore allowing the icons to be rerendered. 
>
> Will be available shortly.
>
> _Originally posted by_ @mallowigi _in_ [https://github.com/mallowigi/a-file-icon-idea/issues/93#issuecomment-683563562_](https://github.com/mallowigi/a-file-icon-idea/issues/93#issuecomment-683563562_)

Any chance this fix / feature is available yet? I'm having a strange intermittent issue where PyCharm just sort of... stops displaying certain icons. Notably, this includes the gutter icons for debugger breakpoints. It's not a breaking issue, it's just *irritating*. 

Honestly, it's *just* irritating enough to warrant typing this out, but not so irritating that I think it's actually worth debugging. I'd be perfectly happy to just click the "reload" button if there was one.

**Comment by mallowigi** [comment]
It's available in the latest version, on the toolbar menu

You can also find it using the find anything popup

--
Elior

**Comment by the-wondersmith** [comment]
> It's available in the latest version, on the toolbar menu You can also find it using the find anything popup
> […](#)
> -- Elior
> On 23 Sep 2020, 23:28 +0300, Mark S. ***@***.***>, wrote: Haven't found the fix for this issue unfortunately, but I found a workaround by adding a button that will manually reload the icons, therefore allowing the icons to be rerendered. Will be available shortly. Originally posted by @mallowigi in #93 (comment) Any chance this fix / feature is available yet? I'm having a strange intermittent issue where PyCharm just sort of... stops displaying certain icons. Notably, this includes the gutter icons for debugger breakpoints. It's not a breaking issue, it's just irritating. Honestly, it's just irritating enough to warrant typing this out, but not so irritating that I think it's actually worth debugging. I'd be perfectly happy to just click the "reload" button if there was one. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

You're a hero!
