### ISSUE TITLE
Rider directory icons do not work

### ISSUE THREAD

**Issue by amstiel** [mallowigi/a-file-icon-idea#112]
The plugin settings don't seem to apply. I unchecked UI, PSI icons, but they still remain changed. Reinstalling plugin does not helps. Reloading IDE does not helps too.

**Atom Material Icons** 28.0
**PhpStorm** 2020.3 EAP

![image](https://user-images.githubusercontent.com/9428948/95413077-dab03b80-096d-11eb-87de-e61ace4f10f9.png)

**Comment by maciekkukuczka** [comment]
In Rider, folder icons do not work (regardless of Rider version)

![image](https://user-images.githubusercontent.com/32330973/95480018-ad728600-098b-11eb-9372-daa318d5a732.png)

**Comment by mallowigi** [comment]
Yes, I can see that the icons are applied no matter what is selected.

I'm investigating to figure out what changed.

**Comment by mallowigi** [comment]
done

**Comment by maciekkukuczka** [comment]
Still directory icons not working in the Rider (2020.3 EAP3)

![image](https://user-images.githubusercontent.com/32330973/95854914-e7f76c80-0d57-11eb-8efd-8499d80eef9c.png)

**Comment by RacerDelux** [comment]
Any update on this guy? I thought I was going crazy myself!

**Comment by mallowigi** [comment]
I havent got the time to look at it but from what i remember Rider doesn't use the FileIconProvider like other Jetbrains products. But I'll take a look as soon as I get into it.

**Comment by RacerDelux** [comment]
Got it thanks! Seems so odd that the file icons would work, but they change how the folder icons work. I also just confirmed that doing a custom icon also fails (I did a simple string regex to test this).

**Comment by Gigacee** [comment]
Same issue here, on Rider 2021.1.2.

**Comment by Drewery-ctrl** [comment]
This Issue Still Persists.

**Comment by kzryzstof** [comment]
It feels like even the Custom Folder Icon assignment is not working...

**Comment by mallowigi** [comment]
Yep, the icon provider extension doesn't work on Rider. I need to investigate about possible workarounds. This could be because Rider is based off Resharper, which is another system.

**Comment by bilalmalkoc** [comment]
Same on me. Rider 2021.3 EAP

**Comment by RacerDelux** [comment]
> Yep, the icon provider extension doesn't work on Rider. I need to investigate about possible workarounds. This could be because Rider is based off Resharper, which is another system.

Any news on this by any chance? Hoping they are adding something to make this possible soon!

**Comment by gigacee** [comment]
Hey, does this mean JetBrains is not interested in addressing this issue?

**Comment by mallowigi** [comment]
As a matter of fact I've addressed the issue, and I will release a new version as soon as I fix the other remaining issues

**Comment by rumfiske** [comment]
This is still a issue for me :(
