### ISSUE TITLE
public_html folder no iconized

### ISSUE THREAD

**Issue by jruedaq** [mallowigi/a-file-icon-idea#113]
in https://github.com/mallowigi/a-file-icon-idea/blob/91e6eb5f04ce13430d5e1bb9a4c640de8822737a/associations.md#L624 no enabled for `public_html` folder

this is public folder in cpanel hostings by default

i was trying find in this code for contribute but i can't found web folder configs

**Comment by jruedaq** [comment]
this is public folder in cpanel hostings by default

**Comment by mallowigi** [comment]
done
