### ISSUE TITLE
Icons in other ide places

### ISSUE THREAD

**Issue by stlr00** [mallowigi/a-file-icon-idea#114]
When I use plugin for file icons. i see it only at project tree. In other places, such as git client - no.
Is that bug of plugin or IDE?
![image](https://user-images.githubusercontent.com/61075639/95632989-6ff72100-0a8f-11eb-9cb5-5ce093dcd56e.png)
![image](https://user-images.githubusercontent.com/61075639/95633012-7ab1b600-0a8f-11eb-8281-6f11398f5c64.png)

**Comment by mallowigi** [comment]
done
