### ISSUE TITLE
.dockerignore icon doesnt work

### ISSUE THREAD

**Issue by stlr00** [mallowigi/a-file-icon-idea#115]
![image](https://user-images.githubusercontent.com/61075639/95674210-53560880-0bb7-11eb-968f-a2f7856ff0b9.png)
So, .dockerignore files mark as plain text in Settings -> Editor -> File Types.

**Comment by mallowigi** [comment]
Indeed, it's because I'm leaving it to the .ignore plugin

**Comment by stlr00** [comment]
But, icons for gitignore and eslintignore are working with or without .ignore plugin

**Comment by mallowigi** [comment]
Maybe, but I don't want to do the same work as .ignore 

They already provided the icons so please use them.
