### ISSUE TITLE
Icon for index.js

### ISSUE THREAD

**Issue by spyinfo** [mallowigi/a-file-icon-idea#116]
Icon for index.js files doesn't working.

![image](https://user-images.githubusercontent.com/36304461/95876158-74675680-0d7b-11eb-8909-1fa3742ece24.png)

WebStorm: 2020.2.1.
Version of Atom Material icons: 27.0

**Comment by mallowigi** [comment]
this is the icon for index.js

https://www.material-theme.com/docs/reference/associations/
