### ISSUE TITLE
Not working with latest EAP

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/a-file-icon-idea#118]

**Comment by mallowigi** [comment]
I've removed the plugin from the marketplace until further notice.

I want to say sorry for the inconvenience, but I'm pretty pissed against JetBrains so please complain to them :)

**Comment by simPod** [comment]
What should we complain about?

**Comment by mallowigi** [comment]
This is the related issue: https://youtrack.jetbrains.com/issue/IDEA-254333

Please follow updates there

**Comment by simPod** [comment]
I see the plugin is up

**Comment by mallowigi** [comment]
Yeah temporarily I've been helped with a workaround using one of material theme's dependencies. It's not ideal but that will do for the time being.

**Comment by simPod** [comment]
Thank you, appreciated! 🚀

**Comment by michabbb** [comment]
@mallowigi i´m following this conversation and activated the icons again (v30.0). the icons inside the directory tree are working, but all other icons inside phpstorm are not... i don´t know if they should... so just FYI....

![image](https://user-images.githubusercontent.com/3524595/98652848-86b5bf80-233c-11eb-881a-c79cf45f2e91.png)

**Comment by mallowigi** [comment]
This is one you need the Material Theme plugin alongside it on latest EAP.

Which version of PHPStorm are you on?

**Comment by michabbb** [comment]
```
PhpStorm 2020.3 EAP
Build #PS-203.5600.44, built on November 6, 2020
Runtime version: 11.0.8+10-b1145.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
```

i am running this: https://plugins.jetbrains.com/plugin/8006-material-theme-ui in version 5.5.1

**Comment by mallowigi** [comment]
Hmmm... what is the state of the "UI Icons" in the plugin settings ?

**Comment by mallowigi** [comment]
In any case try to remove the two plugins and reinstall them from the repository

**Comment by michabbb** [comment]
pardon, what do you mean with "state" ? and what do you mean with "repository". i removed both, installed again, latest version of both... still... the icons inside phpstorm are broken, sorry....

**Comment by mallowigi** [comment]
I mean what is the checkbox state, is it enabled or disabled?

**Comment by mallowigi** [comment]
I just tested on my Mac, and it looks fine. Maybe it's an issue with Windows only?

**Comment by michabbb** [comment]
maybe it´s a windows issue 🤷‍♂️ of course the plugins are "enabled" 😏 

![image](https://user-images.githubusercontent.com/3524595/98656783-5de3f900-2341-11eb-8e90-8674379a3b8e.png)

let me know if there is anything i can do to help u testing....

**Comment by mallowigi** [comment]
I mean, in the Atom Icon Settings

**Comment by michabbb** [comment]
pardon, you mean this window ?

![image](https://user-images.githubusercontent.com/3524595/98657688-6ab51c80-2342-11eb-8e74-fe7de7ccdca7.png)

**Comment by mallowigi** [comment]
Ok this looks fine. I'll check on my old windows machine if that reproduces.

**Comment by mallowigi** [comment]
Can reproduce on windows. Sigh

**Comment by mallowigi** [comment]
I just checked on Windows Webstorm, and now I can't reproduce once again. Please try once more...

**Comment by michabbb** [comment]
@mallowigi I don't see any changes, is there any package I should update?

**Comment by mallowigi** [comment]
I mean try to reinstall both plugins. That's what I did.

**Comment by michabbb** [comment]
pardon, I already did that when we started our conversation. since I don't see any changes here, I don't understand why the result should be different now... that's why I am asking.... of course I can try, don't understand me wrong ;)

**Comment by mallowigi** [comment]
There's a new version of the EAP available, maybe it's because of that

**Comment by michabbb** [comment]
okay, didn't know that and, maybe, could be a useful info in the first place since people are not 24 hours at the pc 😏 will test...

**Comment by michabbb** [comment]
@mallowigi i already told you, my current version is: `203.5600.44` and latest version is `203.5600.44` , so.... as soon nothing has changed, i guess there is no need to test anything again...

**Comment by guyeu** [comment]
reproduce it at latest beta version(203.5784.10), sad.
<img width="1960" alt="image" src="https://user-images.githubusercontent.com/13718160/98763931-b389d580-2415-11eb-8d97-80db0fe62f0d.png">

**Comment by mallowigi** [comment]
Alright, then please stay in touch until the problem is fixed by JetBrains.

**Comment by mallowigi** [comment]
Closing this issue. Will update if things change.

**Comment by michabbb** [comment]
working again with: PhpStorm 2020.3 RC (windows 10) 👍 
Build #PS-203.5981.118, built on November 26, 2020
