### ISSUE TITLE
Kotlin Multi Platform friendly Folder Icons

### ISSUE THREAD

**Issue by mustafaozhan** [mallowigi/a-file-icon-idea#120]
Hello,

Thank you for the nice icon set! 

With Kotlin Multi Platform people started to use some folders in their IntelliJ IDEA and Android Studio. I think it will be really nice to add these folders in correct patters. Yes, you have already related icon sources in project!

Folder Name: `ios` and `iosApp` -> you can use `resourceIOS` icon
Folder Name: `androidApp` -> you can use `android` icon
Folder Name: `backend` -> you can use `server` icon
Folder Name: `desktop` -> you can use `vm` icon (do not use client icon since it can be used as common module for all front end targets)
Folder Name: `buildSrc` -> you can use `sources` or `config` icon

lastly not related with Kotlin multi platform but 
Folder Name: `repository` -> you use `db` icon for `repos` and `repositories` but singular versions are missing so you can use `db` for this as well
Folder Name: `exception` -> you can use `error` icon
Folder Name: `usecase` -> you can use `modals` icon

**Comment by mallowigi** [comment]
great! I'll add those!

**Comment by mustafaozhan** [comment]
@mallowigi  just saw in another project, you can also use `modal` icon for `interactor` folder, I updated the issue also :)
