### ISSUE TITLE
Is there a way to get the old Maven icons

### ISSUE THREAD

**Issue by finalist-io** [mallowigi/a-file-icon-idea#122]
I don't really like the pink V as an icon for Maven. I think intelliJ's icons are still better. 
I added the old icons to the associations but there are still the old icons on the maven panel.
Is there a way to replace the icons with the default ones?

**Comment by mallowigi** [comment]
I'm not planning to give customization for UI icons but you can try to make a custom theme alongside the plugin for your own overrides.

Simply try to follow this guide: https://jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes_customize.html
