### ISSUE TITLE
PDF files show default icon

### ISSUE THREAD

**Issue by liurui39660** [mallowigi/a-file-icon-idea#124]
## Description

In the Project hierarchy, pdf files show the default icon, not the one provided by this plugin.

The icon in the navigation bar and editor tabs are correct.

## System Info

Atom Material Icons 27.0
CLion 2020.2.4
Windows 10

## Screenshot

In Project hierarchy

![image](https://user-images.githubusercontent.com/20491264/99907304-0e290880-2d17-11eb-8437-ec1021a5c510.png)

In the navigation bar and editor tabs

![image](https://user-images.githubusercontent.com/20491264/99907317-213bd880-2d17-11eb-8d26-79742f509012.png)

**Comment by mallowigi** [comment]
Can you post the list of plugins you use?

**Comment by liurui39660** [comment]
24 enabled 3rd party plugins in total, exported from `troubleshooting.txt`

- CMD Support (1.0.5)
- Grep Console (11.2.202.000.0)
- CMake simple highlighter (203.0.1)
- devdocs (1.0.1)
- Material Theme UI (5.3.4)
- Randomness (2.6.1)
- Properties (202.7319.8)
- File Watchers (202.6397.21)
- Atom Material Icons (27.0)
- Path hide (1.0)
- Image Diff (1.7.0)
- License Generator (0.0.10)
- GNU GetText files support (*.po) (202.6397.21)
- ReStructuredText (202.6397.21)
- GitToolBox (202.2.4)
- .ignore (3.2.3.202)
- Makefile support (3.5.1)
- Docker (202.7660.3)
- Nyan Progress Bar (1.14)
- Grazie (202.6948.45)
- Rainbow Brackets (6.12.1)
- TeXiFy IDEA (0.7)
- AsciiDoc (0.31.42)
- PDF Viewer (0.9)

**Comment by mallowigi** [comment]
Can you please disable PDF Viewer and tell me if that helps ?

**Comment by liurui39660** [comment]
No luck, I disabled it and restarted the IDE, the icon is still incorrect.

**Comment by mallowigi** [comment]
The culprit is TeXiFy IDEA

**Comment by liurui39660** [comment]
Yep, now it's correct. I'll open an issue in their repo to report this problem. Thanks for your help.

**Comment by mallowigi** [comment]
PyCharm has the same issue, and I resolved it by adding a Project View Decorator since it was only affected there. However Project View Decorators are bad performance wise so it has to be used with parsimony. 

The bug is open there https://youtrack.jetbrains.com/issue/PY-44417 but I don't think they'll fix them soon.

But you can try to talk to the TeXiFy team, maybe they can circumvent this issue by assigning a lesser priority than the Atom Plugin.
