### ISSUE TITLE
Custom File Association doesn't work as expected

### ISSUE THREAD

**Issue by JamesHarrys** [mallowigi/a-file-icon-idea#126]
I can't modify the index icon to be the regular JavaScript one for an **_index.js_** file.
It gets overridden by the index icon. How can I remedy that?

**Comment by mallowigi** [comment]
it shouldn't. What regular expression are you using ?

**Comment by JamesHarrys** [comment]
I'm using `.*\.js`

**Comment by JamesHarrys** [comment]
Oh! Never mind, I've been trying this for weeks and suddenly it works.
Thanks for your work!
