### ISSUE TITLE
Errors in Intellij Client 2020.3 EAP

### ISSUE THREAD

**Issue by alsoGAMER** [mallowigi/a-file-icon-idea#130]
[stacktrace material icons](https://github.com/mallowigi/a-file-icon-idea/files/5655623/stacktrace_material_icons.txt)

[stacktrace 2 material icons](https://github.com/mallowigi/a-file-icon-idea/files/5655624/stacktrace_material_icons_2.txt)

[induced material icons.txt](https://github.com/mallowigi/a-file-icon-idea/files/5655626/induced_material_icons.txt)

**Comment by mallowigi** [comment]
I know about these errors, but they do not prevent you to work, right?

**Comment by alsoGAMER** [comment]
Kinda, the icons won't show properly sometimes
