### ISSUE TITLE
Nest.js files icon shows wrong

### ISSUE THREAD

**Issue by abnernat** [mallowigi/a-file-icon-idea#131]
Nest.js have similar name pattern like angular, but it is not a same thing. Hoping it can be differeciate. It's kind of frustrate to see some angular icon.
<img width="298" alt="截屏2020-12-09 下午10 35 53" src="https://user-images.githubusercontent.com/10642396/101643257-e6ec6e00-3a6e-11eb-9698-61b81ddf2a56.png">

**Comment by mallowigi** [comment]
I know, I'm working on a way to have "bundles"

**Comment by abnernat** [comment]
Glad to know. Thanks for the reply. ❤️
