### ISSUE TITLE
Support for customizing gutter icons

### ISSUE THREAD

**Issue by skoret** [mallowigi/a-file-icon-idea#133]
Hi! Is there a way to customize a gutter icons?
e.g. [pause.svg](https://github.com/mallowigi/a-file-icon-idea/blob/master/src/main/resources/icons/actions/pause.svg) which is used to mark suspension points in kotlin code

**Comment by mallowigi** [comment]
I'm not planning to provide a way to customize UI icons but you can try to make a custom theme for your needs:

https://jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes_customize.html

There you can override the icons you want.
