### ISSUE TITLE
Freeze my IDE for about half a minute

### ISSUE THREAD

**Issue by AprilViolet** [mallowigi/a-file-icon-idea#134]
**Reproduce:**
When I open a **large project**: such as Spring, when I modify the code, switch to another application, and switch back to the IDEA, My IDEA freezes for about half a minute every time.
**Find:**
So I went to the IDEA folder to find logs, and I found that a lot of logs were printed

![image](https://user-images.githubusercontent.com/40155496/102217218-3a4f3800-3f17-11eb-9107-c7d1b0c0abc1.png)

There are Atom Material File Icons print information in the log file, so I guess it may be Atom Material File Icons error

![image](https://user-images.githubusercontent.com/40155496/102217476-97e38480-3f17-11eb-815d-ab2970e43b96.png)

Then I disabled Atom Material File Icons to reopen the project, it did not print the frozen log, and it would not cause the IDEA to freeze.
I'm not sure if it is an error of Atom Material File Icons or a conflict about plugins.
So now I have to ban Atom Material File Icons in the project:cry:.

This is the log file:
[threadDump-20201215-203351.txt](https://github.com/mallowigi/a-file-icon-idea/files/5696054/threadDump-20201215-203351.txt)

**Comment by mallowigi** [comment]
I'm not really confident about the performance of the plugin, this is not a metric I'm working by. But I've been working with my plugin for a long time now and didn't notice unbearable conditions so far... And I'm working with big projects too.

Maybe try to reduce CPU consumption by excluding folders or by trying to not load all modules in the same window?

**Comment by AprilViolet** [comment]
thank you very much. I will try and continue to observe.
