### ISSUE TITLE
Can't create custom file Icon. 

### ISSUE THREAD

**Issue by SergeyMaltsev** [mallowigi/a-file-icon-idea#135]
Seems Pattern/Icon columns in Custom File Associations are messed.

This is what I've entered there.

![image](https://user-images.githubusercontent.com/57486330/102303417-5093dd00-3f85-11eb-9de5-27c9387b017c.png)

This is what I get after I saved, reopened settings again and tried to edit Icon.

![image](https://user-images.githubusercontent.com/57486330/102303693-f5161f00-3f85-11eb-821b-e6e297362c6f.png)

Sometimes it changes values between columns in unpredictable way.

It works only if I type-in Pattern and then Icon (required to edith both). 
If I try to edit one of them it doesn't work.

Also you could try to press Copy in the Custom File Associations list. This will copy Pattern to Icon and vice versa.

Also couple of questions. 
Is it possible to:
1. Use bundled icons? Like `/icons/files/image.svg` for custom filters?
2. Edit existing Default File Icon filters or copy from them to  Custom File Associations with a simpler way. For example I want another pattern for test files.

**Comment by mallowigi** [comment]
Weird, I'll try to reproduce. 

Regarding your questions:
1. I tried to accomplish that, however doing so slowed the IDE considerably. And the use case is pretty rare, usually people want to use their icons, not use the ones already available for other extensions. What you can do is to download the icons directly on the disk and use them across projects. That's what I'm doing.
2. That might be a good idea, but I have no idea how to do it at the moment. Working with these screens is very cumbersome so this might take a long time
3. Currently I'm planning on releasing two features for this screen (again, don't know when this will happen):
- Ability to turn off specific associations without deleting them
- Importing associations via a xml file, thus creating "reusable bundles"  

As for the copy feature, I can do it I guess.

**Comment by SergeyMaltsev** [comment]
Actually the problem that I can't edit Icon.
I can create it, but then when I try to edit it changes values for Pattern <-> Icon.

Try these steps.
- Open settings
- Create new Icon in Custom File Associations
- Save changes
- Open settings 
- Select created Icon (first line in table)
- Then click copy button at the bottom 

I see that Pattern and Icon for newly line are exchanged.

![image](https://user-images.githubusercontent.com/57486330/102348640-62e53980-3fcc-11eb-80d0-8eb0b4fc3582.png)


Please check if you have correct linking for Pattern/Icon displayed values and stored values.

**Comment by mallowigi** [comment]
Someone just posted a bug similar to this. I'll take a look

**Comment by mallowigi** [comment]
Looks like copy is the issue at hand. Normal creation works fine.

**Comment by SergeyMaltsev** [comment]
Editing of a created one also an issue.
Please try to create new, save then reopen settings and try to edit.
It doesn't work for me.

**Comment by mallowigi** [comment]
Ok i've fixed it. It will be available soon
