### ISSUE TITLE
Default Icon for .flake8 is Django

### ISSUE THREAD

**Issue by MarkKoz** [mallowigi/a-file-icon-idea#136]
This doesn't make sense. Flake8 and the `.flake8` file have no ties to Django. I'm not sure what a good default icon for it should be, but certainly not the Django icon that's misleading.

**Comment by mallowigi** [comment]
Alright. I've added common django files instead: manage.py, settings.py, urls.py, wsgi.py and __init__.py

**Comment by MarkKoz** [comment]
@mallowigi Thanks for addressing this. However, it is a mistake to associate `__init__.py` with Django as that file is a standard Python file used to denote that a directory is a Python package. Packages are created by many Python projects, not just Django ones.

**Comment by mallowigi** [comment]
Yeah I know. I'll fix that for next version.
