### ISSUE TITLE
Request: Database folder icon for persistence/entities etc

### ISSUE THREAD

**Issue by terminalnode** [mallowigi/a-file-icon-idea#138]
Currently a folder called `persistence` or `entities` will get assigned the regular folder/package icon. Would be neat if these could get the same icon as folders called `database` or `repositories`.

**Comment by mallowigi** [comment]
Wouldn't entities be more akin to models?

**Comment by terminalnode** [comment]
Yeah you're probably right, the same icon as for models might be a better fit for `entities`.
