### ISSUE TITLE
Default icon for Python's __init__.py shouldn't be Django icon

### ISSUE THREAD

**Issue by BarisSari** [mallowigi/a-file-icon-idea#139]
<img width="234" alt="image" src="https://user-images.githubusercontent.com/41292272/103085089-b02b6180-45f1-11eb-803b-6eb6c0450fe2.png">

Hello! First of all, thanks for this plugin! I'm using it in all of my Jetbrains IDEs. 

I've created a new basic Python project and I have realised that default icon for `__init__.py` is Django icon. But it shouldn't be. Because each package of Python should have this file, it's not specific to Django. I think it should be a normal Python file icon.

In case it helps, I'm using PyCharm 2020.3.1 and Atom Material Icon 32.0.

**Comment by mallowigi** [comment]
you're right. what about the same icon as index.js ?

**Comment by BarisSari** [comment]
<img width="28" alt="image" src="https://user-images.githubusercontent.com/41292272/103088573-4795b200-45fc-11eb-9db8-a3a7e99f808e.png"> 
This one, right? Yes, I think it would be good.

**Comment by mallowigi** [comment]
ok thanks
