### ISSUE TITLE
Opening and closing multiple files in webstorm seem to refresh icons and open last closed file

### ISSUE THREAD

**Issue by mattgek** [mallowigi/a-file-icon-idea#143]
When I open multiple files and close them with cmd+w and unfold the folded directories, the last open file is automatically reopened. I need auto scroll to and from source in Webstorm, because we have a large monorepo and this is a needed feature so disable the feature is no option.

When I disable the plugin and use the default Webstorm icon set, the issue is not present anymore.
I've been in contact with the webstorm team.
The issue is represented in the attached mov file.

https://user-images.githubusercontent.com/17617446/104352930-93ef5600-5507-11eb-983c-cab678d84fba.mov

**Comment by mallowigi** [comment]
First of all I imagine you want to report an issue in the Material Theme plugin, not the Atom File Icons, right? 
Second of all, I could not reproduce your issue.

Please open the issue in the correct repository but I assume it would be easier to discuss via Slack since this is not a reproducible bug.

**Comment by mattgek** [comment]
Well the thing is that webstorm and Atom repo sent me to you...
I'll try again with Material Theme Plugin guys...

**Comment by mallowigi** [comment]
Well, if you disable the Atom Plugin and leave the Material enabled, does the issue reproduces?

**Comment by mattgek** [comment]
If I disable Atom Plugin the issue is not present anymore

**Comment by mallowigi** [comment]
Hmm... Alright then. But still please connect to the slack channel for a better follow up

**Comment by mattgek** [comment]
Maybe a stupid question but where can I find the link to the slack?

**Comment by mallowigi** [comment]
It's in the bottom of https://www.material-theme.com/ but here you go https://join.slack.com/t/material-theme-ui/shared_invite/zt-4w78iblt-cHXYRYERpuGNbD~TqsD8rg
