### ISSUE TITLE
Latest Versions are not available in Marketplace

### ISSUE THREAD

**Issue by mustafaozhan** [mallowigi/a-file-icon-idea#145]
Hello 👋 

I was waiting long time to get latest update and realised that maybe something is wrong since It has been so long.

When I check the latest version in web it is 35.0.

When I check in Android Studio Stable it is 25.1
When I check in Android Studio Canary it is 27.0 (I expect this to be lower, it is also weird)

Latest versions are not capable to install by Android Studio anymore. When I try to install by manually I get error, is it something that know and intended ?

**Comment by mallowigi** [comment]
True, because Android Studio is still in the 202.* build. It's already 2021 and they are still lagging behind.

**Comment by mustafaozhan** [comment]
@mallowigi they have changed their versioning please check it
https://android-developers.googleblog.com/2020/12/announcing-android-studio-arctic-fox.html

they will not tag anymore with `202.*`

**Comment by mallowigi** [comment]
It's not how they tag it, it's what version is the one that underlays it.

![image](https://user-images.githubusercontent.com/5015756/105614807-7908c580-5dd4-11eb-9d48-4bb39ba85c37.png)

**Comment by mustafaozhan** [comment]
Ohh I see your point thank you for explanation!
