### ISSUE TITLE
SFTP connection icon issues

### ISSUE THREAD

**Issue by rendstack** [mallowigi/a-file-icon-idea#146]
I connect to my remote server with SFTP and develop there. Icons in folders and files are not supported

**Comment by mallowigi** [comment]
What do you mean? When working in remote ftp the plugin doesn't work ?

**Comment by rendstack** [comment]
Folders icons are not shown when I connect with ftp in webstorm

**Comment by mallowigi** [comment]
Hi, the sftp tool window does not execute plugins. Sorry.

**Comment by Youllou** [comment]
Some plugins works with sftp (github copilot, rainbow brackets) so maybe an update made it possible.
