### ISSUE TITLE
Class file icon disappear 

### ISSUE THREAD

**Issue by Kasui92** [mallowigi/a-file-icon-idea#147]
Hi!

I use **PHPStorm 2020.3.1**. After the last update (specifically **35.0**), the classes icon disappeared and the default PHP icon is shown in its place.

I noticed that in the screen with the default icons, that of the classes is not shown, as in the screenshot.

_Can I fix it somehow?_

However, I would like to thank you infinitely for the work you have done as it has allowed me to navigate the projects I manage much easier.

**_Really fantastic!_**

![immagine](https://user-images.githubusercontent.com/15154851/105700059-99d23780-5f08-11eb-8b49-3b1576a1af44.png)

**Comment by mallowigi** [comment]
So this is something new? In previous versions it was working?

I think that could be the same issue as with Python icons. I'll try to implement that but I have my hands full right now so I don't know when it will be it. But if it worked before then that could be a regression.

**Comment by Kasui92** [comment]
I confirm that the class icon was shown in the previous version.

Not a debilitating mistake, of course.
I simply noticed the lack and it seemed correct to report it.

Thanks a lot for the answer!

**Comment by mallowigi** [comment]
Going back to this issue, can't reproduce. Can you give more information?

**Comment by Kasui92** [comment]
For about a month, the icons have reappeared and everything has returned to normal.

I don't even know how to reproduce the problem.

Anyway, thank you for your interest!
I would say that I can close the issue
