### ISSUE TITLE
Display exceptions in the IDEA system UI check box

### ISSUE THREAD

**Issue by ygd-git** [mallowigi/a-file-icon-idea#148]
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021

![image](https://user-images.githubusercontent.com/28592038/106420904-9d306a80-6496-11eb-8dc3-e80d1017690c.png)

**Comment by mallowigi** [comment]
This is probably an issue after updating the plugin, for some reason it doesn't manage to reload the icons after unloading. You need to restart the IDE.

I tried to fix it but couldn't find a fix yet. This is a known issue.
