### ISSUE TITLE
icon for index.js index.ts and index.scss doesn't work

### ISSUE THREAD

**Issue by Clloz** [mallowigi/a-file-icon-idea#155]
<img width="523" alt="Screen Shot 2021-03-19 at 19 50 54" src="https://user-images.githubusercontent.com/17775199/111776109-934eb380-88ec-11eb-93c5-c4b8e9694691.png">

webstorm:2020.3.3 
atom material icons: 35.0

**Comment by mallowigi** [comment]
It's by design: https://www.material-theme.com/docs/reference/associations/

I need to remove the index.html though.
