### ISSUE TITLE
Difference between public and private visibility icon very subtile (Monochrome)

### ISSUE THREAD

**Issue by marcorieser** [mallowigi/a-file-icon-idea#156]
With the monochrome option enabled, the difference between the `public` and `private` visibility icon in the `structure window` is very subtile. Especially on small font size. 
![Bildschirmfoto 2021-04-01 um 08 24 32](https://user-images.githubusercontent.com/2395800/113252807-9ec6b500-92c4-11eb-9cfc-ea69e0c96496.png)

Maybe the icon shape for `public` could be more like an open lock (like the default IDE style)?
![Bildschirmfoto 2021-04-01 um 08 30 29](https://user-images.githubusercontent.com/2395800/113252818-a2f2d280-92c4-11eb-84dd-c106b388a83f.png)

Edit:
or maybe it's possible to use the existing `public.svg` ![public.svg](https://raw.githubusercontent.com/mallowigi/a-file-icon-idea/28b725199bb1933cc01e9cffabdcaa7621aa2b7b/src/main/resources/icons/nodes/public.svg) instead of `c_public.svg` ![c_public.svg](https://raw.githubusercontent.com/mallowigi/a-file-icon-idea/28b725199bb1933cc01e9cffabdcaa7621aa2b7b/src/main/resources/icons/nodes/c_public.svg)

**Comment by mallowigi** [comment]
Hmm, the problem is that they are the default material icons. They are not even editable so everytime I need to update one I need to create svg masks and such which is not an easy feat.

Unless there are new material icons with a new unlocked icon im afraid there's nothing I can do...

**Comment by marcorieser** [comment]
I see the problem with the material icons but the `public.svg` would be perfect because its shape already is a huge difference to the `private` one. It seems that in the structure window the `c_public.svg` is used. Is it possible to switch use the `public.svg` there?

**Comment by mallowigi** [comment]
I can see there is a `lock-open-variant` in the material design icons, so there could be the trick.

**Comment by marcorieser** [comment]
Can I change this in the plugin or is this something you have to do in the plugin for a future release?

**Comment by mallowigi** [comment]
It's not customizable unfortunately, but I'll try to find the time to do it
