### ISSUE TITLE
Black directory icon for unclear reason

### ISSUE THREAD

**Issue by mikehearn** [mallowigi/a-file-icon-idea#159]
This is a beautiful icon set! Some folders are black for me and I don't understand why- from the screenshots and gallery images I've seen, there are no folders that should be entirely black (and it looks wrong/ugly):

![image](https://user-images.githubusercontent.com/971089/113888163-5fb3ca80-97c2-11eb-825c-b6b84e08df0a.png)

This also happens with directories in my source tree. It seems to be the problem for the 'default' folder when nothing else is overlaid on it. Is this intentional?

**Comment by mallowigi** [comment]
The folder color is the same color as the tree text color. But there is an option to change that in the settings.

**Comment by mikehearn** [comment]
Thanks, I was able to fix it now you explained that. I sent 20 bucks as a donation for the great support.

It's a bit odd to see a black icon because it's so different to the brightly colored style - perhaps if the tree text is black (presumably very common) a different default color would work better.
