### ISSUE TITLE
General folder color in dark theme

### ISSUE THREAD

**Issue by ihorvorotnov** [mallowigi/a-file-icon-idea#16]
Just updated the plugin and the icons of general folders become white. Too white on a dark theme, shines too much. PhpStorm 2018.3.1, Plugin 8.1. 

Is it a bug on my install, or it's an intentional change? Tried to reinstall the plugin with deleting PhpStorm's caches, didn't resolve it.

<img width="367" alt="screen shot 2018-12-10 at 13 14 22" src="https://user-images.githubusercontent.com/1066083/49729389-0bde5880-fc7e-11e8-961d-edc6924230e6.png">

**Comment by claudioaze** [comment]
The same icon hides if you are using some white theme like IntelliJ theme.
