### ISSUE TITLE
[Feature Request] Support other SVG Color Patchers.

### ISSUE THREAD

**Issue by Unthrottled** [mallowigi/a-file-icon-idea#161]
This plugin currently overrides the platform's/any other plugin's SVG patcher (is there a specific reason?). It would be nice if this plugin could delegate to the previously installed, then apply its logic (overriding for conflicts). That way the other colors come through for icons that this plugin doesn't patch.

Yes, I know this is the platform's internal API, my IDE yells at me and so does the plugin verifier. If they didn't want me to use it, they shouldn't have made it easy to add it in. :smile:

I have [an example](https://github.com/Unthrottled/normandy-progress-bar/blob/master/src/main/kotlin/io/unthrottled/n7/icon/NormandyColorPatcher.kt) and would be happy to implement it here as well. Would save me trouble from having to write more code in other places.

Just wanted to get your thoughts before I write anything.

**Comment by mallowigi** [comment]
Hmmm... As far as I remember it doesnt override but add on top... This is how I made it possible to enable/disable icon sets.

Do you mean that the plugin has higher priority so other providers such as yours could not be executed?

**Comment by Unthrottled** [comment]
> Do you mean that the plugin has higher priority so other providers such as yours could not be executed?

In a sense, yes. I've gotten to work by letting the other plugin modify the attributes (if any) first, then the current plugin will modify the attributes last (adding it to the top).

In actuality, the set of SVGs that I want to patch are independent of the SVGs this plugins patch. So there really isn't going to be conflicts with styling. I just need these other patchers to be part of the chain so they can act on the SVGs that don't get modified by this patcher (if that makes sense, I've said patcher a bunch and its starting to loose meaning)

**Comment by mallowigi** [comment]
My apologies, I thought you were talking about IconPatchers, not Color Patchers. In my case, there is only one, the `TintedColorPatcher` which colors some icons with the accent/folder color.

```
private void initComponent() {
    colorPatcher = new TintedColorPatcher();
    SVGLoader.setColorPatcherProvider(colorPatcher);

    // Listen for changes on the settings
    connect.subscribe(LafManagerListener.TOPIC, source -> {
      SVGLoader.setColorPatcherProvider(null);
      SVGLoader.setColorPatcherProvider(colorPatcher);

      TintedColorPatcher.refreshThemeColor(getThemedColor());
      TintedColorPatcher.refreshAccentColor(getTintedColor());
    });
    connect.subscribe(AtomConfigNotifier.TOPIC, atomFileIconsConfig -> {
      SVGLoader.setColorPatcherProvider(null);
      SVGLoader.setColorPatcherProvider(colorPatcher);

      TintedColorPatcher.refreshThemeColor(getThemedColor());
      TintedColorPatcher.refreshAccentColor(getTintedColor());
    });
  }
```

How do you want to work around thiss?

**Comment by Unthrottled** [comment]
> How do you want to work around this?

I was going to capture the previously set patcher, and construct a `TintedColorPatcher` with that patcher.

It will eventually look something like this (minus the kotlin and other stuff)
```Kotlin
//.......
fun patchColors(
    svg: Element,
    otherPatcher: SVGLoader.SvgElementColorPatcher?
  ) {
    otherPatcher?.patchColors(svg) // let other patcher do work
    patchChildren(svg, otherPatcher) // let this patcher do its work after
  }

  private fun patchChildren(svg: Element, otherPatcher: SVGLoader.SvgElementColorPatcher?) {
    when (svg.getAttribute("themedPrimary")) {
      "fill" -> svg.setAttribute("fill", NormandyTheme.primaryColorString())
      "stroke" -> svg.setAttribute("stroke", NormandyTheme.primaryColorString())
      "both" -> {
        svg.setAttribute("stroke", NormandyTheme.primaryColorString())
        svg.setAttribute("fill", NormandyTheme.primaryColorString())
      }
    }
//....

**Comment by mallowigi** [comment]
hmm looks good to me :)
