### ISSUE TITLE
"Update Project" icon shows a branching icon

### ISSUE THREAD

**Issue by Zeragamba** [mallowigi/a-file-icon-idea#174]
The "Update Project" icon for GIT currently shows a branching icon, which doesn't relate to pulling changes or updating the branch. 
![image](https://user-images.githubusercontent.com/2325473/116573052-7b4e5480-a8da-11eb-9396-8d04a2ef265e.png)

Can this be updated to show the [download icon] ![image](https://raw.githubusercontent.com/mallowigi/a-file-icon-idea/master/src/main/resources/icons/actions/download.svg) instead?

[download icon]: https://github.com/mallowigi/a-file-icon-idea/blob/master/src/main/resources/icons/actions/download.svg

**Comment by mallowigi** [comment]
This was for historic reasons, it was Chris's idea. But I agree it doesn't make sense anymore

**Comment by Zeragamba** [comment]
Just installed 38, and the update icon is still a branching Icon. I see that there is a really tiny "refresh" circle, that almost unreadable at that size.

**Comment by mallowigi** [comment]
That's the best icon i could have done to be consistent. The arrow you provided is usually made for "download"

**Comment by Zeragamba** [comment]
It's still unfortunately conveying the the wrong verb. 

Potentially, if it was two branches becoming one, it could work a bit better, as that'd be closer to "merge" but that runs into the same problem of not being the right verb.

Another idea could be to replace the refresh circle with the same download icon that you overlay on the current branch icon when there's upstream changes.

**Comment by Zeragamba** [comment]
Also why couldn't the download icon be used itself? Consistency wise, it's from the same resource set as the rest of the icons, and verb wize, it matches closer to the idea of pulling down/downloading changes from the remote repo.

**Comment by mallowigi** [comment]
Because you're not really downloading anything, rather, you're syncing your branch(es). Maybe it's not the greatest icon, but we need to stay consistent here. Please try to see in other apps/IDEs what are the alternative.

**Comment by Zeragamba** [comment]
GitKraken uses a download Icon:
![image](https://user-images.githubusercontent.com/2325473/127343778-c4b6a241-80a2-478b-a69d-281fb4334285.png)

GitHub desktop is a refresh icon:
![image](https://user-images.githubusercontent.com/2325473/127344044-e0b0e894-2cba-469a-ad46-ed63a58c6e91.png)

SoruceTree uses a download icon:
![image](https://user-images.githubusercontent.com/2325473/127344151-65c5dd53-923f-4ed2-86af-3758bd597ac9.png)

VS Code is a download icon:
![image](https://user-images.githubusercontent.com/2325473/127344615-4414c425-f7bb-4a22-a53d-3adaffb8c90c.png)

GitAtomic is a download icon:
![image](https://user-images.githubusercontent.com/2325473/127344817-59a21526-8210-43dd-ad05-bfc12cb6a8d8.png)

Default JetBrains is a download icon:
![image](https://user-images.githubusercontent.com/2325473/127344964-d7512048-f0e8-415c-80a3-042c09de6612.png)

GitBox is a left arrow with word:
![image](https://user-images.githubusercontent.com/2325473/127345285-545e027a-9b79-4711-a897-c0f9556486a7.png)

GitX is a download icon:
![image](https://user-images.githubusercontent.com/2325473/127345366-b6b8450e-53d5-4506-a599-de7d01bc103a.png)

**Comment by mallowigi** [comment]
Sold. I'll change it. Thanks for the investigation :)

**Comment by Zeragamba** [comment]
Thanks, and sorry if I came across as discourteous. I love the icons and It makes navigating my tree of files a heck of a lot easier, and thanks for creating the plugin.
