### ISSUE TITLE
iOS icon folder

### ISSUE THREAD

**Issue by adrianofreires** [mallowigi/a-file-icon-idea#176]
Helo! I am currently using Android Studio 4.2 and Atom Material Icons 27.0 (no update options are appearing), and as the photo shows, the iOS folder has a very different icon. How do I change?
![ios folder icon](https://user-images.githubusercontent.com/38692077/117179105-2bbfcb00-ada9-11eb-90d3-6ebb68c203d2.jpg)

**Comment by mallowigi** [comment]
Hmmm that's weird... what other plugins do you have?

**Comment by adrianofreires** [comment]
This is all plugins intalled 

![image](https://user-images.githubusercontent.com/38692077/117312871-c7aa0f00-ae5b-11eb-9d4b-9b1e2a5f3128.png)

**Comment by mallowigi** [comment]
Is this still reproducible?

**Comment by adrianofreires** [comment]
> Is this still reproducible?

Yes, man! Did I do something wrong?
