### ISSUE TITLE
36.0 update broke the icons on Project View

### ISSUE THREAD

**Issue by undesconocido** [mallowigi/a-file-icon-idea#178]
![2021-05-11 13_01_12-Window](https://user-images.githubusercontent.com/11449491/117805296-15a68480-b259-11eb-9dd9-b00c604ed3cd.png)

Left is 2020.3.2 with Material icons 35.0 vs the most recent 2021.1.1 of IntelliJ IDEA Ultimate and 36.0 on the right.

Package and Project Files views have the folders icons, and most of the files ones, but no the classes.

**Comment by mallowigi** [comment]
Have you tried restarting the plugin? Also check if you don't have the hide file icons option enabled.

**Comment by undesconocido** [comment]
I had to do a clean instalation again of the 2021.1.1... something went wrong in the update I guess and fucked up the folder icons or missplaced them. 

Solved.
