### ISSUE TITLE
Lagging file-tree

### ISSUE THREAD

**Issue by bucha** [mallowigi/a-file-icon-idea#190]
**Describe the bug**
I realized that having Atom Material Icons installed and active, my file-tree behaves very sluggish. Naturally I first opened a ticket at Jetbrains about this behavior but after a back-and-forth with the support I profiled a CPU snapshot and found out that calls to `com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconHeight()` are actually causing too much computation and therefore the sluggish scrolling. After I've disabled Atom Material Icons my scrolling in the file-tree was smooth again.

Please refer to: https://youtrack.jetbrains.com/issue/WI-61296

**To Reproduce**
1. Load up a project with enough files for the file-tree to show a decent scrollbar
2. Scroll up and down in the file-tree

**Expected Behavior**
Butter-smooth scrolling.

**Environment**
PhpStorm 2021.1.4
Build #PS-211.7628.25, built on June 30, 2021
Licensed to Hans Maulwurf
You have a perpetual fallback license for this version.
Subscription is active until June 5, 2022.
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-77-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1919M
Cores: 8
Registry: bigger.font.in.project.view=true, run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: GrepConsole (11.10.211.6086.0), Rider UI Theme Pack (0.9.2), com.andrey4623.rainbowcsv (2.0), com.intellij.ideolog (203.0.27.0), net.seesharpsoft.intellij.plugins.csv (2.17.1), net.vektah.codeglance (1.5.4), org.elixir_lang (11.12.0), org.jetbrains.plugins.go-template (211.6693.44), name.kropp.intellij.makefile (211.7628.1), Dart (211.7665), com.github.jk1.ytplugin (1.2.5), com.intellij.lang.jsgraphql (2.9.1), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.4), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.209), ru.adelf.idea.dotenv (2021.2)
Current Desktop: ubuntu:GNOME

**Comment by mallowigi** [comment]
It doesn't depend on the amount of files. I have also a very huge number of files in the tree and see no difference in performance. However there could be some icons that can cause such performance issues. 

Do you have an example project with the said sluggishness?

**Comment by bucha** [comment]
The projects I'm working on are mainly closed source so I can't really share a project.
However I'm mainly working in PHP environments. So my file tree contains a lot of .php but also .html, .js, .md, .sql and .xml.

The PHP files will be Interfaces, Abstract Classes, Classes, Traits and so on.

I really love the Material icons and would like to continue using them.
Do you have an idea how I could isolate which icons might cause the issue?

**Comment by bucha** [comment]
@mallowigi
Turned out I had to force the IDE to use my GPU for rendering on my Ubuntu workstation by adding these to the vmoptions:
```
-Dsun.java2d.opengl=true
-Dsun.java2d.opengl.fbobject=true
```

After that I was able to re-activate the Material Icons plugin and everything works butter-smooth and looks wonderful as before.
Sorry for the hassle and thank you for all the work you've put in creating the plugin!
