### ISSUE TITLE
Freezes in PhpStorm

### ISSUE THREAD

**Issue by horvathlaszlogyorgy** [mallowigi/a-file-icon-idea#194]
**Describe the bug**
When I save any file in the project, the complete IDE UI freezes for 1-3 secs and the CPU usage jumps & project structure flashing.

**To Reproduce**
1. Open PhpStorm
2. Install the Icon plugin
3. Create new [Laravel project](https://github.com/laravel/laravel)
4. Modify any file, such as write a comment to routes/web.php
5. Save the file
6. The IDE freezes for 1-3 secs because of the high CPU usage, and the project structure is flashing (it is refreshing)

I excluded node_modules / vendor folders from the indexing method. 
I checked the log file but it does not contain useful information.

**Expected Behavior**
Works without freeze

**Environment**
- OS: Windows 10 20H2
- IDE: PhpStorm 212.4746.100, built on July 28, 2021
- Plugin version: 38.0
- I tried with the pure IDE config, and the problem still occur, so there are no another plugins.

**Screenshots**
- No screenshots

**Comment by mallowigi** [comment]
This is due to the "hollow folders" feature. I don't have time to find a better implementation, try to disable the feature if it helps
