### ISSUE TITLE
New python logo

### ISSUE THREAD

**Issue by arihant2math** [mallowigi/a-file-icon-idea#197]
---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
The current python logo seems too dissonant, 

**Describe the solution you'd like**
Perhaps it would look nicer if it was all blue, or blue **and** yellow like the real python logo.

**Describe alternatives you've considered**
Using a custom defined logo, but it would be nicer if it was default.

**Current Logo**
https://github.com/mallowigi/a-file-icon-idea/blob/master/src/main/resources/files/plugins/python/python/pythonFile.svg

**Comment by mallowigi** [comment]
This request has been asked over and over but as I always say I am not planning to change it. You are welcome to use the custom associations with a different color though.
