### ISSUE TITLE
Icons for folders starting with underscores

### ISSUE THREAD

**Issue by TannerHolladay** [mallowigi/a-file-icon-idea#198]
**Is your feature request related to a problem? Please describe.**
I am working on a project with a team, and we use underscores to move folders we use the top. This, however, causes no icons to match any of the patterns since they don't include underscores.

**Describe the solution you'd like**
I'd like for the icon patterns to ignore underscores

**Describe alternatives you've considered**
I've considered using the custom icons, but none of the icons are locally stored and it would take forever to individually add them.

**Comment by mallowigi** [comment]
Interesting. I can add a setting to specify a prefix in general.

**Comment by TannerHolladay** [comment]
That would be perfect!

**Comment by mallowigi** [comment]
In the end I simply added support for leading underscores. It will be available in next version.

**Comment by TannerHolladay** [comment]
Perfect! Much appreciated

**Comment by TannerHolladay** [comment]
I haven't yet seen this show-up. Is there a setting I am missing or has this version not been released yet?

**Comment by mallowigi** [comment]
It should be available, can you provide a screenshot of what you mean?

**Comment by TannerHolladay** [comment]
Here's one folder for example:
![image](https://user-images.githubusercontent.com/48075421/133942687-9754c9b2-9045-48e4-9944-059de4366394.png)

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/133942829-49bbc816-f5bf-4216-9977-f02e61876782.png)

that's odd... make sure you have the latest version, folder icons enabled and not power safe mode

**Comment by TannerHolladay** [comment]
I just realized the folder isn't getting an icon regardless of the underscore... This is in a unity project in Rider. It works on one of my other projects that uses Webstorm.

**Comment by mallowigi** [comment]
Ah Rider. Ok it's a known issue, the directory icon provider doesnt' work on Rider. So please follow with the relevant issue.
