### ISSUE TITLE
PHP class, traits icons are breaks

### ISSUE THREAD

**Issue by AminulBD** [mallowigi/a-file-icon-idea#20]
Hello,

The new update breaks the PHP class and traits icon.

Here is the example before install:
<img width="214" alt="screenshot 2019-01-08 at 20 04 46" src="https://user-images.githubusercontent.com/5006546/50836053-74eee400-1382-11e9-98ce-0cacf5d592b4.png">

Here is the example after install:
<img width="259" alt="screenshot 2019-01-08 at 20 03 53" src="https://user-images.githubusercontent.com/5006546/50836129-a667af80-1382-11e9-8bdb-1e2d7492a5e8.png">

Can you please help me to fix this?

**Comment by AminulBD** [comment]
I don't know why you closed this issue. This issue is not resolved yet with the latest version.

**Comment by ihorvorotnov** [comment]
@AminulBD If you check the source code, you'll see that icons are applied based on file extensions. 

https://github.com/mallowigi/a-file-icon-idea/blob/0fdd66ad863152a87f8603931eabe62f8b502cae/src/main/resources/icon_associations.xml#L394

Both classes and traits are PHP files, with .php extension. Thus, the PHP icon is applied. It is not "broken" I (personally) would rather consider it a feature.

Additionally, for classes and traits you still have an "arrow" icon on the left and a class/trait icon when expanded:

![Screen Shot 2019-03-29 at 17 52 56](https://user-images.githubusercontent.com/1066083/55245370-ac678100-524b-11e9-8203-8b3b6a9a7839.jpg)

**Comment by ihorvorotnov** [comment]
@mallowigi I noticed that at least 2 latest releases actually have default icons for PHP files - rounded class/traits and a standard file icon for "not standard OOP" files (with functions, config arrays, multiple classes in one file etc) - see screenshot below: 

![Screen Shot 2019-08-02 at 17 57 38](https://user-images.githubusercontent.com/1066083/62387807-4d50aa80-b564-11e9-907b-3a3f2afc18e9.jpg)

Is this a planned change or is it a bug and a pink elephant is expected? From the changelog I see that v10 added a new setting - PSI Icons, that "replaces icons about program structure: classes, interfaces, methods, enums etc.". So it is expected that with this turned on some new (custom) icons should be displayed instead? With this setting turned off or on nothing actually changes for me (PhpStorm 2019.1 and 2019.2).
