### ISSUE TITLE
TODO Icons

### ISSUE THREAD

**Issue by mallowigi** [mallowigi/a-file-icon-idea#212]
DOTO:
- SeamIcons
- SeleniumSharedIcons
- TideIcons
- VisualisationIcons
- Xamarin
- 
Nobody cares about:
- SpyJS
- Struts
- SVNIcons
- MPSIcons

**Comment by hua03** [comment]
Hello, I found that the default icon of folder uses original idea folder icon. I suggest that this icon also be replaced with atom icon.
