### ISSUE TITLE
Icon not show for File Java -> Enum

### ISSUE THREAD

**Issue by sercheo87** [mallowigi/a-file-icon-idea#216]
**Describe the bug**
Have install Atom Material Icons v41.0.0 and not load icon on file java of type **Enum**

**To Reproduce**
1. Install v41.0.0
2. Open a project java with type File Java Enum

**Expected Behavior**
Show icon in Enum type.

**Environment**
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Subscription is active.
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Batch Scripts Support (1.0.12), cn.jxzhang.plugin.json-formatter (1.4), de.docs_as_co.intellij.plugin.diagramsnet (0.1.11), commit-message-helper-idea-plugin (1.1.0), com.intellij.ideolog (203.0.27.0), ski.chrzanow.foldableprojectview (1.1.1), org.mayevskiy.intellij.sonar (2.10.1), ru.mobiledev.plugins.uigd (1.2), com.github.mikesafonov.jenkins-linter-idea-plugin (0.5.2), org.jetbrains.plugins.go-template (212.4746.52), String Manipulation (8.15.203.000.3), GrepConsole (11.10.211.6086.0), com.godwin.json.parser (1.4.2), org.asciidoctor.intellij.asciidoc (0.33.19), org.jetbrains.plugins.spotbugs (1.2.4), org.sonarlint.idea (5.3.0.36775), mobi.hsz.idea.gitignore (4.2.0), Gitflow (0.7.7), org.jetbrains.kotlin (212-1.5.30-release-409-IJ4638.7), ru.adelf.idea.dotenv (2021.3.0.212), com.haulmont.jpab (5.4-212), com.mallowigi (41.0.0), com.chrisrm.idea.MaterialThemeUI (6.8.2)
Kotlin: 212-1.5.30-release-409-IJ4638.7

**Screenshots**

![image](https://user-images.githubusercontent.com/1036090/133447392-11352c19-861b-4900-a376-4ea3c191726c.png)

**Comment by Lorenzo0111** [comment]
I have the same problem

**Comment by zatedzernat** [comment]
Same problem after upgrade to v41.0.0

**Comment by mallowigi** [comment]
Fixing. I need to find a svglinter ^^
