### ISSUE TITLE
Missing Folder Icons

### ISSUE THREAD

**Issue by jacobsong** [mallowigi/a-file-icon-idea#218]
**Describe the bug**
Some folder icons do not display anymore.

**To Reproduce**
After upgrading Intellij IDEA to 2021.2.2 *(from 2021.2.1)* and plugin version 41.0.0 *(from 40.0.0)* some folder icons stopped showing. It was working on previous versions.

**Expected Behavior**
All folder icons should be visible

**Environment**
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.13-200.fc34.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 4
Registry: ide.intellij.laf.enable.animation=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi.idea (16.0), com.mallowigi (41.0.0), izhangzhihao.rainbow.brackets (6.21), zielu.gittoolbox (212.7.7), JRebelPlugin (2021.3.2)
Kotlin: 212-1.5.30-release-409-IJ4638.7
Current Desktop: GNOME (Fedora 34)

**Screenshots**

Previous version:
![icons1](https://user-images.githubusercontent.com/5523767/133644653-fc655334-170e-4222-aeeb-1bfafe9f647e.PNG)

Current version:
![icons2](https://user-images.githubusercontent.com/5523767/133645665-c5d30b51-a718-4d01-8b63-1ca3e9670275.PNG)

Settings:
![settings](https://user-images.githubusercontent.com/5523767/133645679-68018b92-810f-4694-bf97-4e7cc5155829.PNG)

**Comment by mallowigi** [comment]
Reproduced... I'll issue a fix asap

**Comment by jacobsong** [comment]
Version 41.1.0 fixed the issue for me
