### ISSUE TITLE
Icons Associations do not save

### ISSUE THREAD

**Issue by Quark03** [mallowigi/a-file-icon-idea#235]
**Describe the bug**
Changes made to the associations tab do not save but still have an unchecked checkbox. 

**To Reproduce**

1. Disable an association
2. Click Apply (observe that the change did happen in the current window)
3. Close IDEA (close it, do not close project or anything weird)
4. Open the IDEA and observe that the icon you changed was reset
5. Open Settings
6. Check that the icon checkbox is unchecked

**Expected Behavior**
I guess it's supposed to save the settings on reopen

**Environment**
WebStorm 2021.2.3
Build #WS-212.5457.55, built on October 18, 2021
For educational use only.
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-38-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1988M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.jinsihou.react.snippets (1.1.0), org.intellij.plugins.postcss (212.5457.18), ru.adelf.idea.dotenv (2021.3.0.212), com.mallowigi (50.2.0), com.intellij.react.css.modules (1.0.1), com.intellij.lang.jsgraphql (3.0.0)
Current Desktop: ubuntu:GNOME

AtomMaterial 50.2.0 Enabled

**Comment by mallowigi** [comment]
Reproduced. Thankfully it's only the disabled state :/

**Comment by Quark03** [comment]
Well, my settings don't save at all. So for me it's not only the showed state :-(

**Comment by mallowigi** [comment]
What do you mean? You just said that the checkbox is unchecked, which is what you did (disabled association).

The only thing I reproduced was that even though it was disabled, the icon would still appear at start
