### ISSUE TITLE
Icons not visible after upgrade to version Idea 2021.3 RC

### ISSUE THREAD

**Issue by jhalehol** [mallowigi/a-file-icon-idea#242]
**Describe the bug**
After I upgrade to version 2021.3 RC icons are not present, if I disable the plugin I am able to see the default icons from the IDE

Using an old version of the IDE and plugin I can see the icons.

**To Reproduce**
1. Upgrade to 2021.3 RC version and plugin to 50.2.0

**Expected Behavior**
Icons visible in the project Tree

**Environment**
IntelliJ IDEA 2021.3 RC (Ultimate Edition)
Build #IU-213.5744.125, built on November 17, 2021
Licensed to Jhon Alexander Holguin Barrera
Subscription is active until November 25, 2021.
Runtime version: 11.0.13+7-b1751.19 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2024M
Cores: 8
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    IdeaVIM (1.8.1)
    PMDPlugin (1.8.21)
    com.mallowigi (50.2.0)
    GrepConsole (12.1.211.6086.0)
    com.oliverlockwood.plugins.jenkinsfile (1.0)
    com.chrisrm.idea.MaterialThemeUI (6.10.1)

Kotlin: 213-1.5.10-release-949-IJ5744.125

Enabled plugins (not bundled)
Atom Material Icons (50.2.0)
IdeaVim (1.8.1)
Material Theme UI (6.10.1)

**Screenshots**
![image](https://user-images.githubusercontent.com/12763618/143448395-344c85f2-2911-498a-bbc6-f2b625e5a210.png)

![image](https://user-images.githubusercontent.com/12763618/143448430-e0ed0be2-f838-48f8-93c0-49beb339596b.png)

**Comment by mallowigi** [comment]
Did you try to restart the IDE? I know that when the plugin updates a restart is necessary

**Comment by jhalehol** [comment]
Hi @mallowigi thanks for your fast response, yes I already restarted it several times and it didn't work, I disabled the addon, and default icons appear immediately, then I enabled again the plugin, and the icons disappear

**Comment by mallowigi** [comment]
What about your settings? Maybe you had the "hide file icons" or "hide directories" toggled?

**Comment by jhalehol** [comment]
Where is this configuration?, as I mentioned I only upgraded IntelliJ version, in the previous version icons were working, I didn't know evet that this option exist to hide icons, so I think that is is using default value

**Comment by mallowigi** [comment]
Settings > Atom Material Icons

**Comment by jhalehol** [comment]
Mmm, yes that was the issue, thank you, however, it's very weird that they were disabled after upgrading the version, because I was using them normally in a previous version 🤔 

thank you

**Comment by mallowigi** [comment]
That's very weird indeed, but I haven't done anything relate dto that.

**Comment by jhalehol** [comment]
Yes, very weird, well thanks for the support, I really appreciate :) , I will close this issue
