### ISSUE TITLE
Color/highlight or Add an icon to a specific file under project files

### ISSUE THREAD

**Issue by ahmed-bhs** [mallowigi/a-file-icon-idea#25]
I have a very important file at the level of my project which is called `veiw.yml`. I would like to color/highlight or put an icon on it, in order to make it more attrective for me. In other words I want color or add an icon on one of my **yml** file at the level of my project files, that match the exactly regex expression `^views.yml$`.
Is there any way I could do the trick with phpstorm or change the phpstorm  <a href="https://plugins.jetbrains.com/plugin/10044-atom-material-icons">  Atom Material Icons </a> plugin configuration to add another icon to his iconslist?

Any idea, help would be appreciated.

[![The view.yml is selected with the cursor][1]][1]

  [1]: https://i.stack.imgur.com/hFafP.png

**Comment by mallowigi** [comment]
There is no possibility to change the icon atm, however you can already create a scope containing your file, then create a file color with that scope.

It’s hard to explain, try to look on the internet about scopes
