### ISSUE TITLE
YAML displayed with i18n icon

### ISSUE THREAD

**Issue by ParticleMon** [mallowigi/a-file-icon-idea#257]
A YAML file with a two-letter filename is displayed with an i18n icon instead of a YAML icon in the Project panel of PyCharm.

**Reproduction**
1. Enable Tools > Atom File Icon Settings > File Icons
2. Name a YAML file (.yaml or .yml) with any two-letter combination (such as 'fo', 'ob', or 'ar').
3. Observe the icon of the file in the Project panel. (The Open File of Project modal is unaffected.)

**Expected**
Regardless of filename, files are displayed in the Project panel with the icon associated with their extension. Specifically, YAML files are always displayed with a YAML icon, never with an i18n icon.

Toggling options, refreshing icons, modifying content of the YAML, overwriting with content from YAML files whose icons are displayed as expected, and invalidating cache do not fix the issue.

Refresh Icons causes the YAML icon to display briefly before it quickly changes to i18n.

**Environment**
Windows
PyCharm 2021.3 (Community Edition)
Atom Material Icons 50.2.0

**Comment by mallowigi** [comment]
Can I ask what kind of file are you using that is 2 letters and is not a language ?

**Comment by ParticleMon** [comment]
> Can I ask what kind of file are you using that is 2 letters and is not a language ?
Data irrelevant to language.

**Comment by mallowigi** [comment]
You can disable the "i18n" extension (or add an association to override the default one) if you want to. Is that file something common or something related to your project?

**Comment by ParticleMon** [comment]
The file is project related.

**Disabling "i18n Languages" in Associations fixed the issue.**

Thanks!

**Comment by mallowigi** [comment]
Please note that there exists a bug where you will have to disable that association every time you restart the project. It has been fixed and will be available shortly, but be aware of that.
