### ISSUE TITLE
java icon in intellij tabs is messy code.

### ISSUE THREAD

**Issue by Clloz** [mallowigi/a-file-icon-idea#259]
java icon in intellij tabs is messy code.
<img width="824" alt="Screen Shot 2021-12-31 at 8 20 14 PM" src="https://user-images.githubusercontent.com/17775199/147823197-d50185d0-7661-4cfb-8b16-155e27470c9a.png">
but the project tool window is normal
<img width="237" alt="Screen Shot 2021-12-31 at 8 20 25 PM" src="https://user-images.githubusercontent.com/17775199/147823199-c74c09c7-1394-4c03-94ce-cd1f4cda5e56.png">

**Environment**
IntelliJ IDEA 2021.3.1 (Ultimate Edition)
Build #IU-213.6461.79, built on December 29, 2021
Runtime version: 11.0.13+7-b1751.21 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Registry:
    ide.experimental.ui.toolwindow.stripes=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.1)
    leetcode-editor (7.3)
    de.ax.powermode (100.001)
    com.wakatime.intellij.plugin (13.1.8)
    com.tabnine.TabNine (0.5.6)
    com.kagof.pokeprogress (1.6.0)
    com.jetbrains.plugins.ini4idea (213.5744.190)
    com.jetbrains.edu (2021.12-2021.3-439)
    com.intellij.plugins.watcher (213.6461.19)
    com.intellij.ideolog (203.0.27.0)
    org.jetbrains.kotlin (213-1.6.10-release-923-IJ5744.223)
    com.mallowigi (53.0.0)
    com.github.copilot (1.1.4.220)
    String Manipulation (8.24.203.5981.1)
    Statistic (4.1.7)
    Key Promoter X (2021.3)
    mobi.hsz.idea.gitignore (4.3.0)
    com.intellij.kubernetes (213.6461.19)
    com.intellij.lang.jsgraphql (3.1.2)
    zielu.gittoolbox (212.8.4)
    org.intellij.scala (2021.3.17)
    izhangzhihao.rainbow.brackets (6.21)
    com.intellij.bigdatatools (213.5449.230)
    com.chrisrm.idea.MaterialThemeUI (6.12.2)

**Comment by mallowigi** [comment]
This means that your files are not part of the classpath
