### ISSUE TITLE
Icon sidebar not showing jar classes properly

### ISSUE THREAD

**Issue by Olzie-12** [mallowigi/a-file-icon-idea#262]
**Describe the bug**
For some reason, on the latest version of IntelliJ and the latest version Atomic Icons all the java icons have been removed? It just shows the java icon. instead of the class icons.

**Expected Behavior**
Should show the correct class icons instead of the java icon.

**Environment**
* Windows 10
* IntelliJ Ultimate 2021.31
* Plugin version 54.0.0
* If needed a list of enabled plugins https://img.olziedev.com/999999K999ttZ_adv999J.png

**Screenshots**
https://img.olziedev.com/GKwq714ir771414714vj.png it shows it correctly in the tab, but not on the sidebar

**Comment by mallowigi** [comment]
You're right, I noticed it. I'm releasing a fix at that same moment.

**Comment by Olzie-12** [comment]
> You're right, I noticed it. I'm releasing a fix at that same moment.

Okay thanks, haha. Its just really tricking me when i'm using it, because this icon normally shows for me personally when the class isn't setup properly haha. Thanks for the fast response and i love the plugin! 

It makes IntelliJ look so much better, JetBrains aren't very good at designing their IDEAs to make them look nice but i love their ides with your plugin!

**Comment by mallowigi** [comment]
Thanks. A fix has been issued that you can download at the plugin page. For the rest it will wait until JB's approval.

There could be other things that broke, as this completely changed the way the plugin works (thanks to JB for ignoring my YouTrack issues for two long years) so languages that would replace the project view icons would not do that anymore. But that also included the PSI icons and other quality of life improvements like my other **Image Icon Viewer** plugin.

**Comment by Olzie-12** [comment]
> Thanks. A fix has been issued that you can download at the plugin page. For the rest it will wait until JB's approval.
> 
> There could be other things that broke, as this completely changed the way the plugin works (thanks to JB for ignoring my YouTrack issues for two long years) so languages that would replace the project view icons would not do that anymore. But that also included the PSI icons and other quality of life improvements like my other **Image Icon Viewer** plugin.

Thank you, I decided to code on my MacBook in the end as the plugin didn’t update haha. I’ll wait for the approval for the plugin, thanks

**Comment by aurimasniekis** [comment]
I guess the same issue is related with PHPStorm too, because all PHP files are now just elephants :D

**Comment by GuguAbrams** [comment]
"Enable file icon" has the opposite effect

![QQ截图202201060916061111](https://user-images.githubusercontent.com/2210040/148312511-583a18aa-324b-4ca2-bd12-63cb125c7d2b.png)
?
![QQ截图202201060917042222](https://user-images.githubusercontent.com/2210040/148312528-32a58952-86fb-4aa4-8cc3-3417a8edb00b.png)

**Comment by aurimasniekis** [comment]
Yeah turning off `Enable File Icons` fixed missing icons :D

**Comment by mallowigi** [comment]
It's been fixed and deployed in version 54.1 but because JetBrains are in holidays at the moment it wasn't approved yet. But I invite you to download it and install it manually.

--
Elior
