### ISSUE TITLE
Github icon

### ISSUE THREAD

**Issue by Blocky38** [mallowigi/a-file-icon-idea#263]
**Describe the bug**

All config.yml get the Github icon not only the files from Github in .github/ ... When I disable "Github Actions" the problem isn't present anymore.

**To Reproduce**
1. Enable the Plugin
2. Create a config.yml at any point in a project

**Expected Behavior**
Icon is not the Github-Icon.

**Environment**
Build #IC-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Plugin version: 54.1.0
OS: Windows 11

**Screenshots**
![Screenshot 2022-01-06 230623](https://user-images.githubusercontent.com/86119630/148458935-8b7d5d8e-4448-4ba7-839e-7ce9346fadcb.jpg)
![Screenshot 2022-01-06 230707](https://user-images.githubusercontent.com/86119630/148459001-4c5e5c0b-94fc-459d-88a3-20cf72632765.jpg)

**Comment by mallowigi** [comment]
I think it should be settings.yml instead, you're right

**Comment by Blocky38** [comment]
It is `config.yml` but only in the `.github` folder and not on every path in the opened project.

**Comment by mallowigi** [comment]
Unfortunately there is no way of using parent directories for icons at the moment.

**Comment by Blocky38** [comment]
Is there any way for me to change it to the settings icon (I would also change all config.yml files to the other icon) and could this issue be "converted" to a request?

**Comment by mallowigi** [comment]
Well you have the Associations settings for this.

--
Elior
