### ISSUE TITLE
Support WebStorm 2022.1 EAP

### ISSUE THREAD

**Issue by ynhhoJ** [mallowigi/a-file-icon-idea#269]

**Comment by DAmNRelentless** [comment]
I don't think more info should be required. Marking it as compatible with 2022.1 should be enough to make it work again.

**Comment by mallowigi** [comment]
Quick update: I just finished fixing all breaking changes issues in the Material Theme UI plugin, after two weeks of constant fixing. I thought this project would be swift and quick, unfortunately JetBrains did it again and the whole plugin doesn't work in 2022 anymore (well, to be precise, some parts still work, mainly the File and Folder Icons, and the custom associations, but the UI Icons is completely broken)

I don't know what they changed and it will take some time to figure it out (plus I'm completely exhausted after working one week non stop for the Material UI). In the meantime, I advise you not to update yet.

**Comment by DAmNRelentless** [comment]
Good to know, thanks for the quick response. Good luck on that end.

**Comment by Unthrottled** [comment]
@mallowigi 

I think it might have to do with the [MainSVGPatcher](https://github.com/mallowigi/a-file-icon-idea/blob/8a9f8a727ac3b3c0ab86a17b711676a7bb84055f/common/src/main/java/com/mallowigi/icons/svgpatchers/MainSvgPatcher.kt#L43). They recently enabled/did something with the svg patching, which made it angry if the caching `digest` returns null (at least it did with [my plugin](https://github.com/doki-theme/doki-theme-jetbrains/issues/483)). My fix was to update the digest anytime the confiig/laf changed, that way the cached icon looks correct.

However, I don't know if that is the case. I was trying to find time to circle back and fix the code I originally put in for the other patcher support. Just haven't figured out to run the IDE with the plugin with the new common/rider build setup. Yay platform updates! <sup><sup>:unamused:</sup></sup> 

Anyways, hope that helps, if I have time in a few days (and you haven't fixed it already) I'll at least see if I need to fix the stuff I put in.

**Comment by mallowigi** [comment]
Hey Alex long time no see :)

I knew about the SVGPatcher and digest, and I managed to fix it, but this is only one of the problems, the one that I gave up is the IconPathPatcher that stopped working. I guess it has to do with this commit:  https://github.com/JetBrains/intellij-community/commit/f64085d4ebebc7fdf00c8080a1ae7bf8e1bf98fc#diff-3be7f8e9583199fd5a2edc32539477d64f37fff8f17fec9a6f5b00d4af2a90f6

I hope they didn't break the ability to patch the icons' path...

**Comment by Unthrottled** [comment]
> I hope they didn't break the ability to patch the icons' path...

I at least know that with the vanilla UITheme (provided by the platform) [icon patching from class path resources like this](https://github.com/doki-theme/doki-theme-jetbrains/blob/8f9287aed77dae9756d46249eb740605d17dddc9/buildSrc/assets/templates/base.laf.template.json#L717) still works, if that helps. I can still have things like the folder/file and UI  icons patched with that method.

Sounds like you've got it under control, for the most part. Good luck with the rest of your 2022 updates! :smiley:

**Comment by mallowigi** [comment]
[Atom Material Icons-60.0.0.zip](https://github.com/mallowigi/a-file-icon-idea/files/8009714/Atom.Material.Icons-60.0.0.zip)

Done. For the impatient, you can download it here until it got approved (and tell me if there are regressions :D )
