### ISSUE TITLE
Missing arrow overlays for symlinked files and folders

### ISSUE THREAD

**Issue by SergeyMaltsev** [mallowigi/a-file-icon-idea#271]
Plugin hides symlink overlay arrows for files and folders.
Please compare left and right pictures.
![image](https://user-images.githubusercontent.com/57486330/155475578-2ab2ec8e-ec4f-4891-9049-330de8805f5e.png)

**Comment by SergeyMaltsev** [comment]
Could I expect some fix for this?

**Comment by liamjones** [comment]
Still an issue

**Comment by SergeyMaltsev** [comment]
Need some update for this. Please fix.

**Comment by SergeyMaltsev** [comment]
Thanks a lot. Now it works in v61.0.
