### ISSUE TITLE
Performance issue in big project for "select in project view" and "always open selected files"

### ISSUE THREAD

**Issue by linaori** [mallowigi/a-file-icon-idea#272]
**Describe the bug**
When this plugin is enabled, it takes several seconds for the file to open in the project view using either of these features. It's slow enough to actually bug out and sometimes never open it at all, or open a previously selected file tab if you switch before it's loaded

**To Reproduce**
Not sure, my project is 20+ years of legacy with 50k+ files in the project. There's a lot of different file types (this is just everything with 50 or more files of that type):
```
  39155 php
   2190 js
   1944 svg
   1299 xml
   1229 map
    615 png
    593 twig
    571 css
    501 gif
    415 md
    410 inc
    397 csv
    351 meta
    240 html
    223 json
    221 fixed
    171 txt
    163 xlf
    135 swf
    129 as
    128 jpg
    124 yml
     90 xsd
     84 z
     84 ttf
     83 xlsx
     73 less
     72 afm
     58 scss
     57 dist
     56 sql
```

So I'd assume that the problem is just the size

**Expected Behavior**
To have the project view open almost as fast as without this plugin

**Environment**

Build #IU-213.6777.52, built on January 28, 2022

Licensed to **************************
You have a perpetual fallback license for this version.
Subscription is active until February 20, 2023.

Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Plugin version: 54.1.0

**Comment by mallowigi** [comment]
Please try to disable "Hollow Folders" and activate "Low Power Mode" and tell me if it improves it

**Comment by linaori** [comment]
Just the "Hollow Folders" setting alone seems to already fix it. While clicking around I still had a few instances where it took a second or so, though most were almost instant, not 10+ seconds anymore or not loading at all. For reference, these are the settings I have:
![image](https://user-images.githubusercontent.com/1754678/155726733-45ae82fa-518e-4fa7-ba67-7c98a3a106cc.png)

**Comment by mallowigi** [comment]
Yeah, the project view decorators is a poor man's solution but is needed in instances when the original icon providers don't apply, such as Rider, JetBrains gateway and such.

I hope I can find a way to optimize it, but I am pretty busy at the moment, that's why I offered the Low Power Mode as a way to turn off these extensions if you're not using Rider/Gateway and experience slowliness.

**Comment by linaori** [comment]
Turning off Hollow folders does the trick for me and works good enough, no complaints here. I'm happy I don't have to turn off the plugin completely 😁

**Comment by NikitaPersefoni** [comment]
I have a very similar experience, although turning off hollow folders didn't help much. However, switching off "File Icons" did resolve this issue and Project View folders started populating on click instantly without `...loading`

**Comment by simPod** [comment]
Indeed, I had the same issue. Disabling File Icons helps as a workaround.

Crosslinking JB youtrack issue https://youtrack.jetbrains.com/issue/IDEA-331662#focus=Comments-27-8122867.0-0
