### ISSUE TITLE
"External Libraries" icons are broken

### ISSUE THREAD

**Issue by Machine-Maker** [mallowigi/a-file-icon-idea#274]
**Describe the bug**
In the External Libraries section of the Project view, the icons for various java files are broken, showing up as (what I imagine is) the "missing icon" image.

**To Reproduce**

Just create a java project, and depend on some library.

**Expected Behavior**
Should be the same icons as java files in the main project view

**Environment**
Build #IU-213.6777.52, built on January 27, 2022
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Atom Material Icons: 54.1.0

**Screenshots**
##### With `Enable File Icons` checked
![image](https://user-images.githubusercontent.com/15055071/155915713-ef94d8f4-1911-4b93-90a5-627736b4377c.png)
##### Without `Enable File Icons` checked
![image](https://user-images.githubusercontent.com/15055071/155915820-ec7938a4-6acf-4c1f-84f2-46ed31352e8b.png)

**Comment by ZekerZhayard** [comment]
I have the same issue

**Comment by Arcomit** [comment]
I have the same issue

**Comment by ZekerZhayard** [comment]
This issue is still present in current revision

**Comment by Machine-Maker** [comment]
Fixed in 61. thanks
