### ISSUE TITLE
Icons are not loaded if UI Icons is off (at start)

### ISSUE THREAD

**Issue by mofada** [mallowigi/a-file-icon-idea#276]
**Describe the bug**

**To Reproduce**

1.Today I updated `WebStorm`, then opened the project and found that the icon was gone, and then tried to disable `Atom`, the icon was displayed, so I think it may be the problem of atom

**Expected Behavior**

when i disable atom plugin

![image](https://user-images.githubusercontent.com/22286246/162903581-cd9ca2e9-f66e-4e67-b8ea-d96d61f1d516.png)

**Environment**

![image](https://user-images.githubusercontent.com/22286246/162902828-21b8962a-2197-4444-a1a5-13f0899174d2.png)

**Screenshots**

- default ： disable ui icon

![image](https://user-images.githubusercontent.com/22286246/162903072-482de7a7-24d1-4eb2-921c-ee4d7279f3c2.png)

- enable ui icon

![image](https://user-images.githubusercontent.com/22286246/162904023-7322a3da-eda7-4ad3-8a3f-b256113bf469.png)

![image](https://user-images.githubusercontent.com/22286246/162903412-1ae15f5f-22b9-43b3-b5f8-a54eee0aefee.png)

**Comment by mofada** [comment]
The icon is also missing

![image](https://user-images.githubusercontent.com/22286246/163084463-fe75988a-1496-46d8-8900-ea85a24b61de.png)

**Comment by mofada** [comment]
and here

![image](https://user-images.githubusercontent.com/22286246/163084545-d2aabf81-f966-4306-93fc-aa3337918db7.png)

**Comment by maxbebaasuro** [comment]
I can confirm that this is a bug. Workaround: Disable the plugin, start webstorm, enable plugin. You need to do it everytime you restart webstorm.

**Comment by mallowigi** [comment]
I haven't updated yet, I have still a branch in progress. Sorry for the troubles.

**Comment by finnan444** [comment]
Updated Goland, have the same bug on Ubuntu
![Screenshot from 2022-04-14 15-16-31](https://user-images.githubusercontent.com/28092100/163389441-7cb2a4c1-dc2a-4b12-bbe3-0c601988c744.png)

**Comment by mofada** [comment]
> I can't reproduce guys. Is it on MacOS ?

i am windows

**Comment by mallowigi** [comment]
I can't test on windows at the moment. For Mac it doesn't reproduce.

**Comment by maxbebaasuro** [comment]
I work on windows. If you explain how to test a prerelease I can give it a try on Tuesday

Beste Grüße

Maximilian Beckenbach
________________________________
Von: Elior Boukhobza ***@***.***>
Gesendet: Thursday, April 14, 2022 4:20:27 PM
An: mallowigi/a-file-icon-idea ***@***.***>
Cc: Maximilian Beckenbach asuro GmbH ***@***.***>; Comment ***@***.***>
Betreff: Re: [mallowigi/a-file-icon-idea] Icon bug when opening project (Issue #276)


I can't test on windows at the moment. For Mac it doesn't reproduce.

**Comment by Drenalol** [comment]
> I can't reproduce guys. Is it on MacOS ?

Yes, Monterey, Mac M1.

First disappear started from some action, can't reproduce, but now i have everytime like below.

JetBrains Rider 2022.1 EAP 10
61 version of plugin

![image](https://user-images.githubusercontent.com/4239087/163472346-322c006a-88a4-44c8-ad35-686c68522e76.png)

![image](https://user-images.githubusercontent.com/4239087/163472372-126579b6-0192-4ee7-a9e8-0981bd64545e.png)

**Comment by 9526xu** [comment]
> > I can't reproduce guys. Is it on MacOS ?
> 
> Yes, Monterey, Mac M1.
> 
> JetBrains Rider 2022.1 EAP 10 61 version of plugin
> 
> ![image](https://user-images.githubusercontent.com/4239087/163472346-322c006a-88a4-44c8-ad35-686c68522e76.png)
> 
> ![image](https://user-images.githubusercontent.com/4239087/163472372-126579b6-0192-4ee7-a9e8-0981bd64545e.png)
> 
> P.S. "Workaround: Disable the plugin, start app, enable plugin" is worked, but after some action it will break.
also Mac M1
IntelliJ IDEA 2021.3 (Ultimate Edition) 
Atom Material Icons 61.0.0 

<img width="524" alt="image" src="https://user-images.githubusercontent.com/15943801/163509839-ece13cf2-a80a-4437-9051-39a2642da69e.png">



<img width="883" alt="image" src="https://user-images.githubusercontent.com/15943801/163509747-02203cb9-cda0-46d0-a652-152f6beb5bae.png">

**Comment by mallowigi** [comment]
I'm also using M1 and not M1, and I don't have this problem. Are you using JDK 17?

**Comment by mallowigi** [comment]
Can you please provide the list of all plugins you use ?

**Comment by Drenalol** [comment]
> Can you please provide the list of all plugins you use ?

![image](https://user-images.githubusercontent.com/4239087/163539185-0405f226-5194-46f5-8812-d5f01560255d.png)

**Comment by Drenalol** [comment]
> I'm also using M1 and not M1, and I don't have this problem. Are you using JDK 17?

![image](https://user-images.githubusercontent.com/4239087/163539803-3017d99e-b225-4e12-b9e9-637be455e327.png)

This helpful for you?

**Comment by mallowigi** [comment]
![CleanShot 2022-04-15 at 10 33 45](https://user-images.githubusercontent.com/5015756/163540034-f85a88ae-be75-4ba4-b417-f89f4600e1e1.png)

So... not really :/

**Comment by mallowigi** [comment]
Still unable to reproduce. I'm afraid this will go unfixed.

**Comment by EmptyDreams** [comment]
I also encountered this problem, many icons became invisible after enabling "Atom Icons".

![QQ截图20220415160020](https://user-images.githubusercontent.com/44894906/163543295-0bc5a996-ae7e-4eaf-af5a-6f5c65f8e2fd.jpg)

![QQ截图20220415160217](https://user-images.githubusercontent.com/44894906/163543414-4a007b12-cc57-4083-8d81-f040575febe8.jpg)

**Comment by Drenalol** [comment]
Step to reproduce for my setup:

1. Open Rider, disable plugin, close Rider
2. Open Rider, enable plugin, icon works until you close Rider
4. Open Rider, icons break

**Comment by mofada** [comment]
i'm update version 61.0.0, still have this problem

![image](https://user-images.githubusercontent.com/22286246/163559969-91efe20b-86d8-40be-a35f-5c8d93393331.png)

**Comment by rushelex** [comment]
Steps to reproduce:
1. Open WebStorm
2. Enable plugin
3. Completely close WebStorm
4. Open WebStorm
Badges will disappear

**Comment by mallowigi** [comment]
Uploading rider.mp4…

What am I missing?

**Comment by rushelex** [comment]
Didn't seem to miss anything, but try the same thing in WebStorm 2022.1

**Comment by mallowigi** [comment]
I'm using Webstorm all the time, and I never encountered this neither

**Comment by OliverSieweke** [comment]
Thank you for looking into this. In case this is of any help, I do encounter the exact same behaviour described by the other users above in the following environment:
- WebStorm 2022.1
    - Atom Material Icons 61.0.0
    - All non bundled plugins disabled
- macOS Montery 12.3.1
    - (not on M1 chip)

**Comment by mofada** [comment]
> rider.mp4 
> What am I missing?

https://user-images.githubusercontent.com/22286246/163574422-d746199a-1d2e-4ccd-bb89-fa2c1b943b2b.mp4

my screen recording

**Comment by mofada** [comment]
@mallowigi I try to run the project, but there are some errors that I don't know how to fix

![image](https://user-images.githubusercontent.com/22286246/163580086-58417ed3-b2f2-41d3-af74-526eab307164.png)

**Comment by mallowigi** [comment]
Can you post your atom material icons settings xml file ?

**Comment by mofada** [comment]
> Can you post your atom material icons settings xml file ?

![image](https://user-images.githubusercontent.com/22286246/163591426-ba1ca8c8-a142-4e97-bd1b-e5ffa27fec1c.png)

**Comment by mallowigi** [comment]
no, xml, it's important.

**Comment by mofada** [comment]
where do i find it

**Comment by mallowigi** [comment]
https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

**Comment by mofada** [comment]
what file in which directory

![image](https://user-images.githubusercontent.com/22286246/163592155-20a93b96-e687-4e2d-a695-5be260a4e6bc.png)

**Comment by mallowigi** [comment]
in the configuration, and it should be named somehting like `atom_material.xml` or something like that

**Comment by mofada** [comment]
i only found this

![image](https://user-images.githubusercontent.com/22286246/163592564-825f4c1a-1c85-4e26-b817-6ac8b1f2482e.png)

**Comment by mallowigi** [comment]
I need to go, please try to google it. If others can help that would be great too.,

**Comment by mofada** [comment]
I search for `atom` in the installation directory of `Webstorm`

![image](https://user-images.githubusercontent.com/22286246/163592745-1d2fa1f4-19ca-445d-bf88-64b5b34c9e84.png)

![image](https://user-images.githubusercontent.com/22286246/163592753-9e15f749-6c4c-4d58-ade0-c9729534d437.png)

**Comment by mofada** [comment]
> @mallowigi I try to run the project, but there are some errors that I don't know how to fix
> 
> ![image](https://user-images.githubusercontent.com/22286246/163580086-58417ed3-b2f2-41d3-af74-526eab307164.png)

@mallowigi Or can you teach me to solve this problem and I try to run the code?

**Comment by rushelex** [comment]
> Can you post your atom material icons settings xml file ?

`/Users/rushelex/Library/Application Support/JetBrains/WebStorm2022.1/jba_config/a-file-icons.xml`

```xml
<application>
  <component name="AtomFileIconsConfig">
    <option name="enabledPsiIcons" value="false" />
    <option name="enabledUIIcons" value="false" />
    <option name="isEnabledUIIcons" value="false" />
    <option name="monochromeColor" value="546e7a" />
    <option name="isEnabledPsiIcons" value="false" />
  </component>
</application>
```

**Comment by OliverSieweke** [comment]
> Can you post your atom material icons settings xml file ?

`Application Support/JetBrains/WebStorm2022.1/settingsRepository/repository/a-file-icons.xml`

```xml
<application>
  <component name="AtomFileIconsConfig">
    <option name="accentColorEnabled" value="true" />
    <option name="enabledDirectories" value="false" />
    <option name="enabledPsiIcons" value="false" />
    <option name="enabledUIIcons" value="false" />
    <option name="themedColorEnabled" value="true" />
    <option name="useHollowFolders" value="false" />
    <option name="isEnabledDirectories" value="false" />
    <option name="isEnabledUIIcons" value="false" />
    <option name="monochromeColor" value="546e7a" />
    <option name="isEnabledPsiIcons" value="false" />
    <option name="isUseHollowFolders" value="false" />
    <option name="isAccentColorEnabled" value="true" />
    <option name="accentColor" value="697991" />
    <option name="isThemedColorEnabled" value="true" />
    <option name="themedColor" value="697991" />
  </component>
</application>
```

**Comment by mofada** [comment]
windows:
`C:\Users\fada\AppData\Roaming\JetBrains\WebStorm2022.1\jba_config\a-file-icons.xml`

```xml
<application>
  <component name="AtomFileIconsConfig">
    <option name="enabledDirectories" value="false" />
    <option name="enabledUIIcons" value="false" />
    <option name="isEnabledDirectories" value="false" />
    <option name="isEnabledUIIcons" value="false" />
    <option name="monochromeColor" value="546e7a" />
    <option name="accentColor" value="1c77cd" />
  </component>
</application>
```

**Comment by mofada** [comment]
> > Can you post your atom material icons settings xml file ?
> 
> /Users/rushelex/Library/Application Support/JetBrains/WebStorm2022.1/jba_config/a-file-icons.xml
> /Users/rushelex/Library/Application Support/JetBrains/WebStorm2022.1/jba_config/atom-icon-associations.xml
> /Users/rushelex/Library/Application Support/JetBrains/WebStorm2022.1/options/a-file-icons.xml
> /Users/rushelex/Library/Application Support/JetBrains/WebStorm2022.1/options/atom-icon-associations.xml

@rushelex  oh, how do you get this format

**Comment by rushelex** [comment]
@mofada just click here 🙂
![CleanShot 2022-04-15 at 21 13 46@2x](https://user-images.githubusercontent.com/41122157/163594537-8318bee4-6f45-4112-ae01-dde8ab9b25ad.png)

or
```xml
<details>
    <summary>Details</summary>

    Content here

</details>
```

**Comment by mofada** [comment]
Understood, thanks ( •̀ ω •́ )y

**Comment by mallowigi** [comment]
> ```
> <application>
>   <component name="AtomFileIconsConfig">
>     <option name="enabledPsiIcons" value="false" />
>     <option name="enabledUIIcons" value="false" />
>     <option name="isEnabledUIIcons" value="false" />
>     <option name="monochromeColor" value="546e7a" />
>     <option name="isEnabledPsiIcons" value="false" />
>   </component>
> </application>
> ```

Managed to reproduce. I'll update when i find the culprit

**Comment by liamjones** [comment]
FYI - looks like you might need both UI and PSI icons enabled to workaround this issue at startup. Enabling only UI wasn't enough for me.

**Comment by OliverSieweke** [comment]
A fix that allows disabling the UI icons would be amazing! Thank you @mallowigi for being so responsive and providing a workaround.

**Comment by 9526xu** [comment]
> 

yes，when Eenable   UI icons  and PSI icons ,the icons appear.

But when only  enable  UI icons ,the icons disappear.

**Comment by 9526xu** [comment]
> FYI - looks like you might need both UI and PSI icons enabled to workaround this issue at startup. Enabling only UI wasn't enough for me.

Yes，when Eenable UI icons and PSI icons ,the icons appear.

But when only enable UI icons ,the icons disappear.

**Comment by mallowigi** [comment]
[Atom Material Icons-61.1.0.zip](https://github.com/mallowigi/a-file-icon-idea/files/8499571/Atom.Material.Icons-61.1.0.zip)

can you test this and tell me if it solves the problem? I don't want to release an update right now as I need to cleanup the project a bit

**Comment by mofada** [comment]
> [Atom Material Icons-61.1.0.zip](https://github.com/mallowigi/a-file-icon-idea/files/8499571/Atom.Material.Icons-61.1.0.zip)
> 
> can you test this and tell me if it solves the problem? I don't want to release an update right now as I need to cleanup the project a bit

it works fine

![image](https://user-images.githubusercontent.com/22286246/163670524-538b4d1f-de73-4537-bee4-2cf03063bbb4.png)

**Comment by liamjones** [comment]
61.1.0 looks to be working fine here too.

**Comment by maxbebaasuro** [comment]
I can also confirm that 61.1.0 works fine on Windows.

**Comment by mallowigi** [comment]
Published!

**Comment by OliverSieweke** [comment]
Amazing! Thank you!
