### ISSUE TITLE
Some icons not rendering in WebStorm 2022.1

### ISSUE THREAD

**Issue by liamjones** [mallowigi/a-file-icon-idea#277]
**Describe the bug**
When the plugin is enabled in WebStorm 2022.1 some UI don't render anymore, they just display a single dot. This only happens when the plugin is enabled but the missing icons even include things that aren't being replaced by the plugin, which is weird... I'm getting this display no matter if I tell the plugin to replace UI/PSI icons or not:

![Screenshot 2022-04-15 at 09 41 35](https://user-images.githubusercontent.com/521341/163548748-01c2e7f3-68de-4835-8953-18a13c7f5bb4.png)

![Screenshot 2022-04-15 at 09 47 52](https://user-images.githubusercontent.com/521341/163548869-dcc7d49e-e918-4591-898f-1d036f2680c8.png)

![Screenshot 2022-04-15 at 09 48 21](https://user-images.githubusercontent.com/521341/163548914-5666c667-2143-446c-b49c-f995e7b620f3.png)

The problem goes away again when the plugin is disabled. It might be an IDE change/bug? I didn't encounter this in the 2021.* WebStorm builds.

**To Reproduce**
1. Use WebStorm 2022.1 (or another 2022.1 IDE I suspect)
2. Enable plugin
3. Restart IDE

**Expected Behavior**
All icons display correctly

**Environment**
WebStorm 2022.1
Build #WS-221.5080.193, built on April 10, 2022
Licensed to Liam Jones
Subscription is active until October 14, 2022.
Runtime version: 11.0.14.1+1-b2043.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    wallaby.js (1.0.238)
    rasarts.espresso.light.theme (1.2.0)
    quokka.js (1.0.332)
    com.wakatime.intellij.plugin (13.1.14)
    com.thvardhan.gradianto (4.5)
    com.markskelton.one-dark-theme (5.5.2)
    com.jetbrains.darkPurpleTheme (1.3)
    com.jetbrains.CyanTheme (1.3)
    com.intellij.ideolog (203.0.28.1)
    com.herokuapp.vuesion (1.9.2)
    com.github.mturlo.intellij.theme.spacegray (1.4.2)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    com.4lex4.intellij.solarized (2.4.0)
    coderpillr.theme (1.0.0-rc.3)
    izhangzhihao.rainbow.brackets (6.21)
    com.mallowigi (61.0.0) (also happened w/ plugin version 60.0.0 before I updated it this morning)
    com.atlassian.bitbucket.references (2022.1.200)

**Comment by mallowigi** [comment]
Please look for open issues before reporting.
