### ISSUE TITLE
IDE icons disappear in v61

### ISSUE THREAD

**Issue by SergeyMaltsev** [mallowigi/a-file-icon-idea#278]
**Describe the bug**
After enabling plugin some IDE icons disappear in toolbar and other places.

**To Reproduce**
1. Enable pugin v61
2. Restart IDE

**Screenshots**
![image](https://user-images.githubusercontent.com/57486330/163700040-8db72c72-6eaf-4fd1-8eb1-0da66da204db.png)

**Comment by mallowigi** [comment]
update to 62
