### ISSUE TITLE
Folder Icon doesn't work on Rider

### ISSUE THREAD

**Issue by MassimilianoOreto** [mallowigi/a-file-icon-idea#280]
**Describe the bug**
The Folder icon doesn't work on JetBrain Rider

**To Reproduce**

1.Install plugin
2.Restart Rider

The folder icon change but not load the different icon. On Webstorm it work correctly

**Expected Behavior**
Apply the right icon on folder

**Environment**
JetBrains Rider 2022.1

It should contain:
Windows 11
JetBrains Rider 2022.1

![image](https://user-images.githubusercontent.com/51315867/164623036-05a288f9-cb49-4bdf-a293-c3cdbac9be60.png)

**Comment by Abdelraman** [comment]
java.io.FileNotFoundException: \icons\files\php.svg (The system cannot find the path specified)
