### ISSUE TITLE
Unable to see which files/folders are symlinks

### ISSUE THREAD

**Issue by sparkbuzz** [mallowigi/a-file-icon-idea#285]
**Is your feature request related to a problem? Please describe.**
I can't see which folders in my file explorer in Webstorm are symlinks.

**Describe the solution you'd like**
Normally Webstorm displays a little chain link to indicate symlinks, but with the Atom Icons, it's not possible to see any indication of symlinked folders and/or files.

**Describe alternatives you've considered**
n/a

**Additional context**

**Without Atom Folder Icons**
_note the chain link on the **components** folder_

![Screenshot 2022-05-11 at 21 40 16](https://user-images.githubusercontent.com/612695/167932356-ee8d8fc2-3a38-410c-b9be-14c7b51e4027.png)

**With Atom Folder Icons**

![Screenshot 2022-05-11 at 21 40 30](https://user-images.githubusercontent.com/612695/167932341-5a8e8a7c-371b-4249-890b-533f7f6baf48.png)

**Comment by mallowigi** [comment]
I've fixed this in a latest version. Which version are you on?
