### ISSUE TITLE
Vertical padding in custom icon size

### ISSUE THREAD

**Issue by taimast** [mallowigi/a-file-icon-idea#286]
**Describe the bug**

When updating the version to 64, there is no large icon function in the settings, and the customized icon size leaves too large vertical gaps between the files, which is very inconvenient.

**Expected Behavior**

Return the `Big Icons' icon
**Environment**

Windows, PyCharm 2022.1 (Professional Edition), Plugin version 64.0.0

**Comment by mallowigi** [comment]
Custom Size is the extension of Large Icons, so by setting the size to 20 you'd be able to reproduce the previous behavior.

Can you elaborate about the issues you mentioned?

**Comment by taimaskhanov11** [comment]
Unfortunately, I can't make the same size as before. The vertical gaps between the files are too large, and they cannot be changed in any way. The more I increase the size of the icons, the larger the gaps, if the size of the icons is reduced, then the gaps are still relatively large

**Comment by mallowigi** [comment]
But the gaps were made to prevent icons "crushing" onto one another...

Can you show a screenshot of what do you mean "too large"?

I could add a setting to control that padding but I want to make sure that it's something that makes sense

**Comment by geng130127** [comment]
Folder color does not change after opening file

**Comment by taimast** [comment]
current -  63.00
![image](https://user-images.githubusercontent.com/81189712/184982598-94e75d67-1691-4ff7-bc4b-5a47465674b2.png)

after - 64.00
![image](https://user-images.githubusercontent.com/81189712/184982744-dc5fbf55-e316-427f-9d6d-d4e8e61c3438.png)

**Comment by taimast** [comment]
![image](https://user-images.githubusercontent.com/81189712/184982824-30b24214-d8d5-48dd-91a2-11c7c5ac1a81.png)
everywhere, these huge gaps

**Comment by taimast** [comment]
when there are a lot of files, in total these gaps take up too much space

**Comment by mallowigi** [comment]
Fixed on latest version
