### ISSUE TITLE
Support Webstorm EAP 2022.2

### ISSUE THREAD

**Issue by BartKoppelmans** [mallowigi/a-file-icon-idea#288]
**Describe the bug**
Error message: "The plugin 'Atom Material icons' was explicitly marked as incompatible with the current version of the IDE."

The plugin was working fine with EAP 2022.2 until two days ago. Please let me know whether there is some information missing or if I can do something to help.

**To Reproduce**
1. Start Webstorm.

**Expected Behavior**
The plugin should load successfully.

**Environment**
WebStorm 2022.2 EAP
Build #WS-222.2680.4, built on May 25, 2022
Licensed to WebStorm EAP user: Bart Koppelmans
Expiration date: June 24, 2022
Runtime version: 17.0.3+7-b463.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1004M
Cores: 8
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.ideolog (203.0.30.0)
    com.godwin.json.parser (1.4.1)
    com.github.copilot (1.1.23.1578-agent)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    com.dubreuia (2.3.0)
    String Manipulation (9.4.1)
    mobi.hsz.idea.gitignore (4.4.1)
    org.zalando.intellij.swagger (1.1.2)
    com.intellij.database (222.2680.4)
    izhangzhihao.rainbow.brackets (6.23)
    com.chrisrm.idea.MaterialThemeUI (7.6.1)
    ru.adelf.idea.dotenv (2022.2)

**Screenshots**
Not applicable.

**Comment by mallowigi** [comment]
Done. You can find it here: https://plugins.jetbrains.com/plugin/10044-atom-material-icons/versions

It will be available when JetBrains approves.
