### ISSUE TITLE
Incompatible with IntelliJ Version 2022.2 EAP Build #IC-222.2680.4

### ISSUE THREAD

**Issue by garyc0221** [mallowigi/a-file-icon-idea#289]
**Describe the bug**
Plugin 'Atom Material Icons' (version 64.0.0) was explicitly marked as incompatible with the current version of the IDE therefore the plugin doesn't work at all. Is there any plans to update this to work with the EAP or will it work once there is an official release of this version.

**To Reproduce**
1. Install plugin with IntelliJ version listed above.

**Expected Behavior**
Plugin should load if compatible. 

**Environment**
IntelliJ IDEA 2022.2 EAP (Community Edition)
Build #IC-222.2680.4, built on May 25, 2022
Runtime version: 17.0.3+7-b463.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 7000M
Cores: 8
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.javafx (1.0.4)
    net.scrumplex.fxmlhelper (1.0)
    com.github.copilot (1.1.23.1570)
    com.andrey4623.rainbowcsv (2.0.2)
    Statistic (4.1.10)
    Docker (222.2680.7)
    org.dpytel.intellij.plugin.maventest (0.0.21)
    zielu.gittoolbox (212.9.0)
    com.chrisrm.idea.MaterialThemeUI (7.6.1.1)
    izhangzhihao.rainbow.brackets (6.23)

Kotlin: 222-1.6.21-release-357-IJ2680.4

**Screenshots**
![image](https://user-images.githubusercontent.com/79464926/170943324-fa7cf547-8da6-4782-b411-50849529bd54.png)

**Comment by mallowigi** [comment]
Already submitted for moderation, this will be available in a few days
