### ISSUE TITLE
Icon request: Artisan as Laravel icon

### ISSUE THREAD

**Issue by Grawl** [mallowigi/a-file-icon-idea#29]
There is Laravel icon for `*.blade.php` files, we can use it for Laravel [`artisan`](https://github.com/laravel/laravel/blob/master/artisan) file. Maybe other color but the same shape.

**Comment by ihorvorotnov** [comment]
@Grawl Since artisan is a cli script wouldn't it be better to use "run script" icon? Also, Laravel has a new/updated logo which will be released with v6 soon. See https://laravel-news.com/laravel-v6-announcement

**Comment by Grawl** [comment]
run script is ok i think
