### ISSUE TITLE
Why some folders has filling and some not?

### ISSUE THREAD

**Issue by max-prtsr** [mallowigi/a-file-icon-idea#295]
Not sure if it's a bug or intentional
Looks like folder is not filled if I have a file opened somewhere down in it.

![image](https://user-images.githubusercontent.com/84035280/172760691-db35ccbf-6dfa-4f6d-bdf7-72de89d5a847.png)

Can it be disabled?

**Comment by mallowigi** [comment]
Hollow folders setting
