### ISSUE TITLE
Suggest to change the icon of Python files

### ISSUE THREAD

**Issue by mshzsh** [mallowigi/a-file-icon-idea#296]
I think Python file icons are very monotonous and boring, I think it would be much better if a combination of blue and yellow is used.
![monitor-1](https://user-images.githubusercontent.com/41986782/174975896-db51d34c-0511-4c20-9979-081addbe5b0e.png)
![monitor-2](https://user-images.githubusercontent.com/41986782/174976355-acf9cbb6-a225-46e5-bbe9-d4a640b85fc8.png)

**Comment by mallowigi** [comment]
Sorry, I refuse. Icons should be one-colored, except for specific exceptions, and python is not one of them. You can use the custom associations to replace with the icon you want.
