### ISSUE TITLE
Plugin not working on JetBrains Client (Remote Development)

### ISSUE THREAD

**Issue by belliel** [mallowigi/a-file-icon-idea#299]
**Describe the bug**
Not working in Jetbrains Client (Goland) (Remote development)

**To Reproduce**

1. Start new client, install remote ide, install extension, restart

**Expected Behavior**

Icons is showing

**Environment**

JetBrains Client 2022.1.3
Build #JBC-221.5921.26, built on June 22, 2022
Runtime version: 11.0.15+10-b2043.56 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
Controller in Remote Development (GO)
GC: G1 Young Generation, G1 Old Generation
Memory: 1504M
Cores: 8
Registry:
    suggest.all.run.configurations.from.context=true
    rdclient.backend.actionHandlers=false

Non-Bundled Plugins:
    ru.adelf.idea.dotenv (2022.1)
    com.mallowigi (64.0.0)
    com.intellij.plugins.vscodekeymap (221.5921.12)
    com.intellij.plugins.monokai.colorscheme (221.5921.16)
    com.intellij.plugins.colorful.darcula.colorscheme (221.5921.12)
    atom-one (1.5.1)

**Screenshots**

<img width="274" alt="image" src="https://user-images.githubusercontent.com/33688736/177309491-968792a5-aadc-46f6-b2f6-d005a2f98687.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/33688736/177310010-5fe6ed32-9254-48e2-9d86-5c04372ea4d2.png">

**Comment by t0rb3n** [comment]
@belliel 

>  Runtime version: 11.0.15+10-b2043.56 aarch64

Seems to be the same issue as me and some other people. Take a look at [my comment here](https://github.com/mallowigi/a-file-icon-idea/issues/297#issuecomment-1198135604) on how to (possibly) fix this.

**Comment by lsalazarm99** [comment]
Same here. Something I noted is that it works in the new UI (ide.experimental.ui) but not in the default one. Also, the associations' settings don't show the icons either. They just show a path, like "\icons\files\github.svg".

**Comment by meski17** [comment]
I have a similar issue. Only java icon is not shown.
![image](https://user-images.githubusercontent.com/30213495/185337692-59cc5fad-3e2a-4257-8a69-2a3b05ead3a3.png)
Do you know how to fix that? :)

**Comment by mallowigi** [comment]
It's called PSI Icons

**Comment by mallowigi** [comment]
Closing this. I saw this happening but it's not like I have the tools that allow me to fix it. The main functionality is there though, I can see the file and folder icons and custom associations, it's only the UI Icons that are affected.

Probably, the IconPathPatchers being an internal API, it's not working out of the box to patch the UI icons. There's not much I can do here, unless I can find some documentation or API on how to debug remotely.

**Comment by StanByes** [comment]
Hello @mallowigi 

I want to reopen that because I'm currently experimenting this issue with all my JetBrains' IDE in Remote Development for some months.
The file icons work but not the folder icons like that, on Intellij IDEA :

<img width="193" height="172" alt="Image" src="https://github.com/user-attachments/assets/bd307dab-8196-4dcc-9cc3-150acf27b46d" />

**Comment by mallowigi** [comment]
the icons issue should be added in the Atom material Icons repository.

In any case I think with the help of AI we might be able to find a solution for these issues hopefully.

**Comment by twinkle311** [comment]
目前如何在远程开发模式下使用？
