### ISSUE TITLE
Icons not appear properly (PyCharm 2022.1.4)

### ISSUE THREAD

**Issue by ZorinArch** [mallowigi/a-file-icon-idea#300]
**Describe the bug**

Hi,

when i create file and name it [index.htm] or [index.js] show like on photo below

**To Reproduce**
Create structure like in photo.

**Expected Behavior**
Icons shows properly

**Environment**

PyCharm 2022.1.4 (Professional Edition)
Build #PY-221.6008.17, built on July 20, 2022
Licensed to cat method
You have a perpetual fallback license for this version.
Subscription is active until June 1, 2023.
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.18.13-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 4
Non-Bundled Plugins:
    org.rust.lang (0.4.174.4743-221)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    intellij.webp (221.6008.15)
    com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
    com.markskelton.one-dark-theme (5.6.0)
    com.intellij.plugins.vscodekeymap (221.6008.13)
    org.intellij.plugins.postcss (221.6008.13)
    com.intellij.apacheConfig (221.6008.13)
    com.godwin.json.parser (1.4.1)
    com.andrey4623.rainbowcsv (2.0.2)
    color.scheme.One Dark Pro (0.3)
    XPathView (221.6008.15)
    org.asciidoctor.intellij.asciidoc (0.37.32)
    W3Validators (221.6008.15)
    String Manipulation (9.5.0)
    Refactor-X (221.6008.17)
    Key Promoter X (2022.2)
    mobi.hsz.idea.gitignore (4.4.0)
    org.jetbrains.plugins.vue (221.6008.13)
    spy-js (221.6008.15)
    intellij.prettierJS (221.6008.13)
    cucumber-javascript (221.6008.13)
    com.jetbrains.lang.ejs (221.6008.13)
    com.intellij.tailwindcss (221.6008.13)
    com.intellij.plugins.webcomponents (221.6008.13)
    com.intellij.plugins.html.instantEditing (221.6008.13)
    com.jetbrains.plugins.jade (221.6008.13)
    com.github.masahirosuzuka.PhoneGapIntelliJPlugin (221.6008.17)
    com.dmarcotte.handlebars (221.6008.17)
    com.jetbrains.plugins.meteor (221.6008.13)
    com.deadlock.scsyntax (221.6008.13)
    NodeJS (221.6008.15)
    Karma (221.6008.13)
    com.mallowigi (64.0.0)
    org.jetbrains.plugins.node-remote-interpreter (221.6008.13)
    ru.adelf.idea.dotenv (2022.1)
    Dart (221.6008.17)
    izhangzhihao.rainbow.brackets (6.25)
    com.mallowigi.colorHighlighter (11.0.0)

Current Desktop: KDE

**Screenshots**

![idea-icons](https://user-images.githubusercontent.com/62427713/180600398-191750e9-65f2-4a46-bbb1-71637d5c1317.png)

**Comment by mallowigi** [comment]
Not a bug. This is done on purpose to represent index files.
