### ISSUE TITLE
[Feature request] Create new port to vscode-icons

### ISSUE THREAD

**Issue by ZorinArch** [mallowigi/a-file-icon-idea#301]
Hi,

please create new port project from [vscode-icons](https://github.com/vscode-icons/vscode-icons) to JetBrains IDEs.

This will offer more options to users, it's very beautiful real icons. 

All you need just replace current icons with one's in vscode-icons.

Thanks,

**Comment by mallowigi** [comment]
Sorry, won't happen. I already have too much work on my hands, I don't plan to add any more work. Besides I'm not sure I have the rights to do so.

You're free to make your own plugin based off this one though :)
