### ISSUE TITLE
[FEATURE] icon for `npm-shrinkwrap.json` 

### ISSUE THREAD

**Issue by jkowalleck** [mallowigi/a-file-icon-idea#303]
npm knows multiple lock file formats. besides `package-lock.json` it knows.
see <https://docs.npmjs.com/cli/v8/configuring-npm/npm-shrinkwrap-json>

the icon theme already puts a proper icon for `package-lock.json`.
but  `npm-shrinkwrap.json`  is detected as arbitrary json file. 

request: `npm-shrinkwrap.json`  has the same iscon  as the current  `package-lock.json` has

**Comment by mallowigi** [comment]
done

**Comment by jkowalleck** [comment]
thanks for adding this.
as a metter of documentation, the shrinkwrap was added to atom icons via 
[1.7.16](https://github.com/file-icons/atom/blob/master/CHANGELOG.md#1716---2016-07-05)
