### ISSUE TITLE
Latest release breaks padding in rider units tests / solution explorer

### ISSUE THREAD

**Issue by peppy** [mallowigi/a-file-icon-idea#309]
**Describe the bug**

Until the most recent update (v72 featuring no change notes?) padding was normal, but now it is missing and makes Rider's UI look very cramped.

**Environment**

```csharp
JetBrains Rider 2022.2.2
Build #RD-222.3962.23, built on August 21, 2022
Licensed to Dean Herbert
Subscription is active until June 14, 2023.
Runtime version: 17.0.4+7-b469.44 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 32
Metal Rendering is ON
Registry:
    search.everywhere.actions=false
    search.everywhere.toolwindows=false
    ide.mac.pressAndHold.workaround=false
    search.everywhere.configurations=false
    select.run.configuration.from.context=false
    ide.web.preview.enabled=false
    run.popup.move.folders.to.top=true
    ide.balloon.shadow.size=0
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    org.nik.presentation-assistant (1.0.10)
    com.jetbrains.darkPurpleTheme (1.3)
    com.intellij.resharper.HeapAllocationsViewer (2022.2.0)
    com.jetbrains.rider.android (222.3962.23)
    com.intellij.ideolog (203.0.30.0)
    AceJump (3.8.8)
    IdeaVIM (1.11.1)
    Abc.MoqComplete.Rider (2022.2.0.2)
```

**Screenshots**

I've included a comparison versus rider without the material icons plugin, and also one comparing to the previous release where this issue was not present.

## Unit tests

Expected (vanilla rider):

![JetBrains Rider 2022-09-02 at 07 13 58](https://user-images.githubusercontent.com/191335/188079967-8150a930-4063-4888-a5fd-5b2cd9710158.png)

Actual (v72):

![JetBrains Rider 2022-09-02 at 07 15 34](https://user-images.githubusercontent.com/191335/188080243-4274994f-b884-4d96-85bc-cf226c94531c.png)

## Solution explorer

Expected (v71):

![JetBrains Rider 2022-09-02 at 07 17 45](https://user-images.githubusercontent.com/191335/188080619-a9ebaa64-3508-422b-a7ca-7afb44186e6f.png)

Actual (v72):

![JetBrains Rider 2022-09-02 at 07 15 08](https://user-images.githubusercontent.com/191335/188080150-70761d1c-6181-4ba7-8317-c2f549fe2109.png)

Note that I am using presentation mode, if that means anything.

**Comment by mallowigi** [comment]
Looks like the defaults were wrong, I'll increase them. In the meantime you can still configure it via the options.
