### ISSUE TITLE
Disabling PSI icons stops working in IDEA 2019.2

### ISSUE THREAD

**Issue by lehvolk** [mallowigi/a-file-icon-idea#31]
After upgrading to 2019.2 setting for disabling PSI icons is not working.

IDEA:
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
macOS 10.14.6

**Comment by mallowigi** [comment]
I can't reproduce

**Comment by lehvolk** [comment]
It's broken for Kotlin sources. Seems for other languages it's working fine. Thought that the problem is in Kotlin plugin.

**Comment by mallowigi** [comment]
will be fixed next release

**Comment by lehvolk** [comment]
Thanks. Pretty nice plugin. I love it a lot.
