### ISSUE TITLE
ng2 rounting module icon not showing

### ISSUE THREAD

**Issue by p5hema2** [mallowigi/a-file-icon-idea#311]
**Describe the bug**
When you generate a ng2 rounting module a file is created with the name 
[yourname]-routing.module.ts

in the current regex the ".module" is missing

#306

**To Reproduce**
1. ng g m home --routing
CREATE src/app/home/home-routing.module.ts (247 bytes)
CREATE src/app/home/home.module.ts (272 bytes)

**Expected Behavior**
correct mapping

**Environment**
Build #IU-222.3739.54, built on August 16, 2022
Atom File Icon 72.0

**Advice**

```
// change
.*\[._-]routing\.(dart|[tj]s)$
// to
.*(\.routing|-routing\.module)\.(dart|[tj]s)$
```

**Comment by mallowigi** [comment]
I think the error lies in the `\[` that should be `[`

I'll fix it

**Comment by p5hema2** [comment]
and the file type ".module" is still missing
