### ISSUE TITLE
Plugin for vscode

### ISSUE THREAD

**Issue by giovanniiapaolo** [mallowigi/a-file-icon-idea#313]
I was wondering if it was possible to have the extension for vscode.

**Comment by mallowigi** [comment]
Hi, no, it's not planned for the moment. I have too much work to do, and besides there are already plenty of themes in VSCode that do the same.

**Comment by giovanniiapaolo** [comment]
Hi, thanks for the reply. I understand, unfortunately for vscode nobody
sets the icons used by you. You did a great job anyway! have a good time

Il mer 14 set 2022, 11:53 Elior Boukhobza ***@***.***> ha
scritto:

**Comment by mallowigi** [comment]
I've started working on it. I think I can reuse what others did for a minimal amount.

**Comment by giovanniiapaolo** [comment]
Very well, I appreciate this. I think it can have good success

Il sab 17 set 2022, 21:01 Elior Boukhobza ***@***.***> ha
scritto:

**Comment by mallowigi** [comment]
Closing this since it has no point being here. I'll update whenever the plugin is ready.
