### ISSUE TITLE
Icons disappear momentarily after appearing

### ISSUE THREAD

**Issue by aggKartik** [mallowigi/a-file-icon-idea#314]
**Describe the bug**
When the idea is launched or the 'Refresh Icons" button is pressed on the toolbar. The icons will appear for a brief second and then disappear. This only affects the file icons specifically. Folder icons are still present and so are the ones on the toolbar and everywhere else.

**To Reproduce**

1. Launch ide / refresh icons
2. Notice they appear briefly
3. Then notice they disappear

**Expected Behavior**

1. Icons should stay loaded and appear

**Environment**
RubyMine 2022.2.1
Build #RM-222.3739.56, built on August 16, 2022
Runtime version: 17.0.3+7-b469.37 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
    ide.editor.tab.selection.animation=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.6.0)
    zielu.gittoolbox (212.9.9)
    com.mallowigi (72.0.0)
    NodeJS (222.3739.16)
    com.chrisrm.idea.MaterialThemeUI (7.9.0)

**Screenshots**

https://user-images.githubusercontent.com/24238951/190535820-4ff854ce-af26-4d83-bdaa-027bf596398e.mov

**Comment by mallowigi** [comment]
Yeah I'm aware of this issue but I have no idea what can cause it. Too much hassle to figure out.

You're free to try helping out.

**Comment by aggKartik** [comment]
Hey I figured it out. For some reason the "Hide UI Icons" setting got flipped during an update, I never flipped it so it's intriguing that it got messed haha. So turning it back fixed the issue.
 
![image](https://user-images.githubusercontent.com/24238951/192167475-fd837ab9-423a-4629-b6a2-9ef654bd1bad.png)
