### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by Malkom** [mallowigi/a-file-icon-idea#315]
I'm not sure it's a bug so I put it in feature request.

I really like this plugin but I can't see anymore the tooltip on icons. Indeed, I always forgot some keykind and I want to remember it.

For example, when I'm on the debug mode, I always forgot the keybind for the step (F7 / F8  /F9 / etc...) so I put my mouse over an icon to see it keybind. But with this plugin, I can't see it anymore.

Any idea ? or may be it's normal ?

**Comment by mallowigi** [comment]
Finally got some time to get back on this

<img width="427" alt="CleanShot 2022-12-17 at 21 05 31@2x" src="https://user-images.githubusercontent.com/5015756/208258741-e476f17b-de79-48c9-bf57-10c52b1764ba.png">

Looks fine to me. Maybe you could give more details?

**Comment by Malkom** [comment]
Oh thanks for the answer... I don't know why but on my side I don't have the tooltip...

![image](https://user-images.githubusercontent.com/441034/208877282-d7e9b3c2-2252-4194-add0-163333ad2dd1.png)

Same thing without Atom Icons...

So it's not an issue from your plugin... Sorry and thanks again for this awesome plugin ;)
