### ISSUE TITLE
New UI icons not showing on initial load

### ISSUE THREAD

**Issue by thearrow** [mallowigi/a-file-icon-idea#322]
**Describe the bug**
Upon first opening the IDE, the Atom Material UI Icons for the new UI do not display. After manually toggling the "New UI Icons" off then back on in the Atom Material Icons Settings, the UI icons display properly.

**To Reproduce**
1. Open any IDE with the new UI enabled
2. Notice the stock UI icons are displayed
3. Open the Atom Material Icons Settings
4. Uncheck the "New UI Icons" item
5. Click "Apply"
6. Re-check the "New UI Icons" item
7. Click "Ok"
8. Notice the Atom Material UI Icons are now properly displayed

**Expected Behavior**
Atom Material UI Icons for the new UI should display when first opening the IDE.

**Environment**
Note: I have also reproduced this bug in the latest PyCharm EAP (2022.3) with the "New UI" setting enabled as of 10/15/2022.

PyCharm 2022.2.3 (Professional Edition)
Build #PY-222.4345.23, built on October 10, 2022
Runtime version: 17.0.4.1+7-b469.62 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 4
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    name.kropp.intellij.makefile (222.4345.14)
    com.markskelton.one-dark-theme (5.7.0)
    org.intellij.plugins.hcl (222.4345.14)
    com.intellij.plugins.macoskeymap (222.4345.14)
    com.intellij.plugins.expui (0.4)
    com.github.leomillon.uuidgenerator (4.5.1)
    com.dubreuia (2.3.0)
    String Manipulation (9.5.1)
    zielu.gittoolbox (212.9.9)
    mobi.hsz.idea.gitignore (4.4.2)
    **com.mallowigi (73.0.0)**
    intellij.prettierJS (222.4345.14)
    com.intellij.tailwindcss (222.4345.14)
    NodeJS (222.4345.14)
    com.leinardi.pycharm.pylint (0.14.0)
    com.leinardi.pycharm.mypy (0.14.0)
    com.koxudaxi.pydantic (0.3.13)
    ru.adelf.idea.dotenv (2022.2)

**Screenshots**

Initial load of IDE (stock UI icons in left and right toolbars):
<img width="1280" alt="Screen Shot 2022-10-15 at 12 27 23 PM" src="https://user-images.githubusercontent.com/447736/195997863-fd958158-eebf-4e2b-bb49-fa4de6ade5dc.png">

Need to manually toggle this checkbox:
<img width="992" alt="Screen Shot 2022-10-15 at 12 27 44 PM" src="https://user-images.githubusercontent.com/447736/195997905-9358af71-6edd-4e3e-884f-6f5dbf646b2a.png">

Then the proper UI icons display in left and right toolbars:
<img width="1280" alt="Screen Shot 2022-10-15 at 12 28 00 PM" src="https://user-images.githubusercontent.com/447736/195997913-8142e829-bb0b-49f2-9209-256dbbdc6398.png">

**Comment by thearrow** [comment]
Additionally, I have recreated this bug (on a different machine) on the latest PyCharm EAP (2022.3) with no other plugins installed:

PyCharm 2022.3 EAP (Professional Edition)
Build #PY-223.6160.21, built on October 5, 2022
Expiration date: November 4, 2022
Runtime version: 17.0.4.1+1-b629.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    **com.mallowigi (80.0.0)**

**Comment by mallowigi** [comment]
This has been fixed and planned for next release.
