### ISSUE TITLE
Add symlink overlays in file search results

### ISSUE THREAD

**Issue by SergeyMaltsev** [mallowigi/a-file-icon-idea#325]
Is it possible to add symlink arrow overlays in file search results for file icons?
I know it is not even natively supported in IDE. 
But may be you have some idea how to add this?

P.S. Thanks for resolving this issue with overlays previously.
https://github.com/mallowigi/a-file-icon-idea/issues/271

**Comment by mallowigi** [comment]
IF it's not supported natively, I doubt it. Nevertheless I'm adding it to some backlog, let's give it a shot.
