### ISSUE TITLE
Folder icon request

### ISSUE THREAD

**Issue by mustafaozhan** [mallowigi/a-file-icon-idea#326]
Hello 👋
Using it with great pleasure and would like mention that it would be nice to add folder icon for dependency incetion related packages 
ie.
`di`, `injection`, `injector` ...

Many projects has dependency injection uses similar folder names, i know the `di` for android for sure, i have seen others too but these are the ones I remember. if you know any please add them too :)

I think it would be nice to add a folde icon with a `syringe` 💉

**Comment by mustafaozhan** [comment]
up

**Comment by mustafaozhan** [comment]
up

**Comment by mallowigi** [comment]
Thanks for upping :) the project is a bit on a hiatus right now but once all is over I'll get back to it I promise!

**Comment by mustafaozhan** [comment]
No worries, take your time :) I will continue my war with `stale` bot 😅

**Comment by mustafaozhan** [comment]
up

**Comment by mallowigi** [comment]
done

**Comment by mallowigi** [comment]
Please wait for next version, it will happen soon

**Comment by mustafaozhan** [comment]
Ohh thanks a lot! 🎉
