### ISSUE TITLE
Bad Angular associations

### ISSUE THREAD

**Issue by mariusvn** [mallowigi/a-file-icon-idea#329]
**Describe the bug**
The angular component icon assotiate with all files that contains .component. , it is also the case with the services and i imagine every angular association.

**To Reproduce**
1. create a file named `test.service.dart`
2. There it is, the angular icon pop up

**Expected Behavior**
the dart icon should show

**Environment**
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022

Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Plugin version: 73.0.0

**Screenshots**
![File Browser showing the problem](https://i.imgur.com/5eUiBQ9.png)

**Comment by mallowigi** [comment]
It's part of the package. If you don't want it you need to override it in the custom associations.
