### ISSUE TITLE
New UI - default run/debug configuration icons disappear after UI loads when plugin is active

### ISSUE THREAD

**Issue by liamjones** [mallowigi/a-file-icon-idea#331]
**Describe the bug**
I'm trying out the new UI in WebStorm. When the Atom UI icons are not used the default WebStorm icons on the run/debug blue bar display initially and then shortly after disappear, replaced with a single pixel black dot at the top left of the icon's 'container'.

If 'UI icons' are turned on in the plugin, they replace properly as expected.

**To Reproduce**
1. Have UI icons disabled in the plugin
2. Switch to the new UI

**Expected Behavior**
New UI's default icons display in the run configurations bar when UI icons are disabled in the plugin.

**Environment**
WebStorm 2022.3
Build #WS-223.7571.168, built on November 28, 2022
Licensed to Liam Jones
Subscription is active until October 14, 2023.
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    com.herokuapp.vuesion (1.9.2)
    co.giammar.kyle.shadesmear (0.3.0)
    com.4lex4.intellij.solarized (2.4.0)
    com.github.zcg.love-your-eye-theme (1.0.5)
    com.thvardhan.gradianto (4.5)
    org.toml.lang (223.7571.117)
    com.jetbrains.CyanTheme (1.3)
    wallaby.js (1.0.253)
    com.jetbrains.darkPurpleTheme (1.3)
    com.github.mturlo.intellij.theme.spacegray (1.5.1)
    aishwarya18102000.starlight (1.0.0)
    com.linden.lumio-theme (1.0)
    quokka.js (1.0.366)
    com.github.catppuccin.jetbrains (2.0.6)
    com.funk.sage.theme (1.0.4)
    com.intellij.ideolog (203.0.30.0)
    com.markskelton.one-dark-theme (5.7.1)
    com.elliotwaite.cyberpunk_theme (1.0.12)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    com.jetbrains.grayTheme (1.3)
    com.github.nakedsnake26.nierautomatatheme (1.1.1)
    coderpillr.theme (1.0.0-rc.3)
    com.wakatime.intellij.plugin (14.1.2)
    rasarts.espresso.light.theme (1.2.0)
    ru.adelf.idea.dotenv (2022.3)
    com.atlassian.bitbucket.references (2022.1.220)
    org.sonarlint.idea (7.2.0.56810)
    com.mallowigi (80.0.0)
    se.piksel.intellij.themes.prpl (0.6.0)
    izhangzhihao.rainbow.brackets (2022.3.5)

**Screenshots**
Default icons for New UI (plugin disabled):
<img width="348" alt="image" src="https://user-images.githubusercontent.com/521341/205499909-c3416a88-5117-415d-95b0-ed4038629da7.png">

Atom UI icons enabled for New UI:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/521341/205499957-08b3c91b-e8c9-4b3d-a1df-ac0311dcb970.png">

Atom UI icons disabled for New UI:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/521341/205499983-3a2a0d2b-3c24-41c9-b149-70cf0e90c923.png">

**Comment by bitjerry** [comment]
me too

**Comment by mallowigi** [comment]
I cant reproduce, but wait for next version, I did a lot of improvements.

**Comment by liamjones** [comment]
Just updated to 81.0.0, still happening here when UI icons are disabled.

**Comment by mallowigi** [comment]
Quick question: is it working if you turn on the "EXperimental UI icons" ?

**Comment by mallowigi** [comment]
I can confirm that it works. And it makes sense. Since both the New UI and the Atom Material plugin replaces the original icons, they cannot live together, so in order to display the Atom Icons, the New UI Icons have to be disabled. Therefore, if you disable the Atom Icons but do not re-enable the New UI Icons, you'll be left out without icons.

Maybe I need to think of a solution to automatically enable the New UI Icons if the UI Icons are disabled and the user is on the New UI.

**Comment by liamjones** [comment]
> Quick question: is it working if you turn on the "EXperimental UI icons" ?

Oh, I had missed that option entirely, my bad. For anyone else's reference:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/521341/208861633-ad3ced15-3a04-4822-9f67-9170e693f872.png">

Yeah, if that's turned on all is fine. Your explanation makes total sense.

> Maybe I need to think of a solution to automatically enable the New UI Icons if the UI Icons are disabled and the user is on the New UI.
> 
> But I won't do it now, because I don't want to, and I have a lot of other tasks awaiting.

Yeah, that sounds like the only improvement that could be made but I can see how it's not a high priority. The manual settings change is a fine fix for now. 👍
