### ISSUE TITLE
The value of Custom Icon Line Height is not applied at start

### ISSUE THREAD

**Issue by taimast** [mallowigi/a-file-icon-idea#343]
**Describe the bug**
When restarting , it constantly resets the values of Custom Icon Size . Visually shows 20, but actually resets to an unknown value. If you specify 19 and again 20, then everything is fixed until the next restart

**To Reproduce**
1. Restart

**Expected Behavior**
So the vertical distance corresponds to what I specified, even when restarting

**Environment**
PyCharm 2022.3.1 (Professional Edition)
Build #PY-223.8214.51, built on December 20, 2022
Licensed to 
You have a perpetual fallback license for this version.
Subscription expired on December 30, 2022.
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    documentation.show.toolbar=true
    ide.experimental.ui=true
    editor.minimap.enabled=true

Non-Bundled Plugins:
    org.rust.lang (0.4.185.5086-223)
    com.github.copilot (1.1.38.2229)
    com.chesterccw.excelreader (2022.12.1-203.223)
    String Manipulation (9.6.1)
    AceJump (3.8.10)
    FluentLanguage (0.3.2)
    com.wakatime.intellij.plugin (14.1.3)
    izhangzhihao.rainbow.brackets (2023.1.0)
    com.koxudaxi.pydantic (0.3.17)
    com.mallowigi (85.1.0)
    zielu.gittoolbox (213.10.5)

It should contain:
* OS (Windows)
* Pycharm 2022.3.1
* 85.1.0

It should contain:
* OS (Windows)
* Pycharm 2022.3.1
* 85.1.0

**Screenshots**
When i restarting
![image](https://user-images.githubusercontent.com/81189712/212929255-b6cf578a-3ba6-45eb-801c-ecb1df27b3db.png)
![image](https://user-images.githubusercontent.com/81189712/212931376-6e88d4a5-586f-4e45-b5d1-5586047114f2.png)

When i specify again 20
![image](https://user-images.githubusercontent.com/81189712/212931566-156a70fe-2759-49c4-a16b-c650b83faef7.png)
![image](https://user-images.githubusercontent.com/81189712/212931592-61336f1d-04d5-4792-bb42-899cbda025c0.png)

**Comment by mallowigi** [comment]
Are you perhaps referring to the line height?

**Comment by mallowigi** [comment]
Fixed, but I don't have a release planned yet
