### ISSUE TITLE
If file name start with "[]", the file icon will be wrong

### ISSUE THREAD

**Issue by Gargantua7** [mallowigi/a-file-icon-idea#345]
**Describe the bug**

If file name start with "[]", the file icon will be wrong

I don't know what file's icon this is but I'm sure it's wrong
And it didn't happen in the previous version
Also appears on the browser plugin, so I think it might be a problem with the regex or the priority setting

**To Reproduce**

Create file and named to `[]*.*`

**Expected Behavior**

eg. Kotlin file should show _kotlin.svg_ ...

**Environment**

IntelliJ IDEA 2022.3.2 (Ultimate Edition)
Build #IU-223.8617.56, built on January 26, 2023
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0

com.mallowigi (85.1.0)

**Screenshots**

![image](https://user-images.githubusercontent.com/49100066/216119259-652916e5-d378-469a-af7c-edbe55bea2ac.png)

**Comment by mallowigi** [comment]
The regex for slug should be `[.*].(js|kt...)`

That's because slugs are usually [<slug>].js 

Imo it's not something new.

Can I ask you why you need to have such file names if not for slugs?

**Comment by Gargantua7** [comment]
> The regex for slug should be `[.*].(js|kt...)`
> 
> That's because slugs are usually [].js
> 
> Imo it's not something new.
> 
> Can I ask you why you need to have such file names if not for slugs?

just like `[<id>]<title>.kt`
I found the regex for the slug in the ide settings, it is `^\[.*\].*$`

**Comment by mallowigi** [comment]
No but I mean, this is exactly what a slug file is... You should try to disable the associations if you don't want it
