### ISSUE TITLE
Icon request: storage types

### ISSUE THREAD

**Issue by komodovaran** [mallowigi/a-file-icon-idea#35]
Common Python-related storage types including .h5, .npz, .pickle/.pkl don't have any icon.

Also, it seems that unrecognized files get the system default icon instead of e.g. a theme default, which kind of breaks with the theme. Is that by design or a limitation?

**Comment by mallowigi** [comment]
I’ve never thought about a theme default, especially since this is an icon theme. What do you have in mind?

**Comment by komodovaran** [comment]
Maybe a greyish spin on the OS defaults?

Windows:
<img width="70" alt="Screenshot 2019-10-19 at 11 44 07" src="https://user-images.githubusercontent.com/20357875/67142871-e474f680-f265-11e9-9bfa-5f750e01d556.png">

MacOS:
<img width="70" alt="Screenshot 2019-10-19 at 11 44 02" src="https://user-images.githubusercontent.com/20357875/67142872-e474f680-f265-11e9-8520-86de31f6c3e6.png">

Right now, the problem is, if there's no icon available, some other default application will hijack the icon, at least on MacOS:
<img width="453" alt="Screenshot 2019-10-19 at 11 47 41" src="https://user-images.githubusercontent.com/20357875/67142914-4afa1480-f266-11e9-8349-0b22519d3d73.png">

**Comment by mallowigi** [comment]
That's true but I specifically did that so icons not registered with the plugin would still use the icon provided by other plugins. For instance, my plugin doesn't support stuff like .helmignore, .flooignore, .ebignore etc... However such extensions are supported by the .ignore plugin, so the plugin would still display the icons provided by .ignore. 

So yeah, basically h4/h5/whatever that is neither supported by any plugin would display the default icon.

Maybe in the future when I'll implement custom associations you'll be able to undo this. Not for now however.
