### ISSUE TITLE
Update Netlify Logo

### ISSUE THREAD

**Issue by Hrishikesh-K** [mallowigi/a-file-icon-idea#351]
On March 7, 2023, Netlify updated their logo: https://www.netlify.com/blog/netlify-new-logo/

The plugin should update its set of logos to adapt to this change. I was willing to submit a PR, but it appears the icons are part of a private repo: https://github.com/mallowigi/a-file-icon-idea/blob/ce24649b5e5f9ace1a5d19a50f2e029dc697772c/common/src/main/java/icons/IconAssociations.kt#L822-L824

The new logos are available for download from here: https://www.netlify.com/press/#logos

**Comment by mallowigi** [comment]
It's not a private repo: https://github.com/mallowigi/iconGenerator

**Comment by Hrishikesh-K** [comment]
Sorry, I clicked here on `iconGenerator` here and it shows me Page Not Found, so I thought that 😅 

<img width="456" alt="image" src="https://user-images.githubusercontent.com/11403551/224494843-bfdfbcaf-4a71-4778-b87e-67eb7153ecfb.png">

Submitted a PR: https://github.com/mallowigi/iconGenerator/pull/124

**Comment by Hrishikesh-K** [comment]
The above PR has been merged, so feel free to update the plugin when you've a chance (responded just to keep stalebot from kicking in). If this issue doesn't need to remain open for you to merge the changes, feel free to close it.
