### ISSUE TITLE
Settings not (all?) applied after first launch

### ISSUE THREAD

**Issue by JoachimR** [mallowigi/a-file-icon-idea#354]
**Describe the bug**

After first starting intellij some icons still have colors and all other settings have not been applied yet. Only if I make some small change in the settings and apply it, all settings finally get applied. 

**To Reproduce**

1. Restart intellij
2. Check if plugin settings are applied

**Expected Behavior**

Settings are applied without having to first make changes to the plugin settings

**Environment**

Macos Ventura
IntelliJ IDEA 2022.3.3 (Ultimate Edition)
Plugin version 85.1.0

**Screenshots**

<img width="932" alt="Screenshot 2023-03-15 at 19 16 23" src="https://user-images.githubusercontent.com/2596911/225405077-46bf78da-42a4-448e-ba91-26bd49d13e5a.png">

**Comment by mallowigi** [comment]
I don't understand. What settings are not being applied?

**Comment by JoachimR** [comment]
the line height is too high, the custom icon size is too big and the UI icons are still colored. 

If I change the custom icon size from 12 to 13 (or vice versa) and apply settings, everything gets in place and it will look like as I want it:


![bug](https://user-images.githubusercontent.com/2596911/225640953-0ba0971b-cb75-490e-bd25-ef6b8f1e018e.gif)




Does that make more sense?

**Comment by JoachimR** [comment]
seems like this has been resolved in the new intellij version 2023.1
