### ISSUE TITLE
Arrow icon for directory not changing

### ISSUE THREAD

**Issue by nunoh** [mallowigi/a-file-icon-idea#36]
I just installed this plugin and everything seems to be working apart from the arrow for the directory.

It shows me like this:

![wrong](https://user-images.githubusercontent.com/1161423/67945504-5989e980-fbdf-11e9-8aae-5156a078f286.png)

instead of like this:

![right](https://user-images.githubusercontent.com/1161423/67945503-58f15300-fbdf-11e9-9d2e-bf36c6f89baf.png)

**Comment by asilvadesigns** [comment]
this is occuring for me as well

**Comment by mallowigi** [comment]
Yes, arrows are unsupported since 2019.3. I'll try to find a way to restore them

**Comment by asilvadesigns** [comment]
Ah, gotcha, thank you for responding!

**Comment by mallowigi** [comment]
Will be fixed in 20.0
