### ISSUE TITLE
How can I change specific icons?

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [mallowigi/a-file-icon-idea#360]
Yes, how can I say that I don't want a specific icon and use another?

**Comment by mallowigi** [comment]
Please use the Discussions for such questions. And do you mean file associations or UI Icons? Because you can customize the file associations all you want, that includes disabling them. But not for UI Icons.

**Comment by FleetAdmiralJakob** [comment]
I mean how can I change an icon for a specific item type?
