### ISSUE TITLE
In the new UI, the color of the relevant buttons running in the upper right corner is very striking.

### ISSUE THREAD

**Issue by tlerbao** [mallowigi/a-file-icon-idea#367]
In the new UI, the color of the relevant buttons running in the upper right corner is very striking. I hope to optimize it.

![image](https://user-images.githubusercontent.com/20442232/236420805-a2d458bb-455e-439a-8461-74990a0832ca.png)

**Comment by mallowigi** [comment]
This is more an issue for the Material Theme rather than this repository...

**Comment by tlerbao** [comment]
> This is more an issue for the Material Theme rather than this repository...

@mallowigi This is not Material Theme,
is https://github.com/varrcan/oceanic-dark-theme,

They said it might be a-file-icon-idea problem haha

https://github.com/varrcan/oceanic-dark-theme/issues/5

**Comment by mallowigi** [comment]
So if I understand correctly, you want to be able to change the color of the icons of these buttons, not the background color?

**Comment by tlerbao** [comment]
<img width="162" alt="CleanShot 2023-06-06 at 15 28 21@2x" src="https://github.com/mallowigi/a-file-icon-idea/assets/20442232/58c2f073-1978-490e-b460-3be0b27eb29b">

@mallowigi The highlight color of these two buttons, or the background color is too abrupt.

**Comment by mallowigi** [comment]
You can't change the icons color (except by applying the monochrome icons feature), and the bg color is property of the theme.
