### ISSUE TITLE
Navigation tree overlapping while in presentation mode

### ISSUE THREAD

**Issue by DanielRamosAcosta** [mallowigi/a-file-icon-idea#369]
**Describe the bug**
While in presentation mode, the project tree is seen like this:
<img width="1512" alt="image" src="https://github.com/mallowigi/a-file-icon-idea/assets/11427028/71a19170-99f7-42af-844b-c941b7a9e067">

After disabling this plugin, the error is gone. It happens in both the new and old UI.

**To Reproduce**

1. Install the plugin
2. Enter presentation mode
3. Press Command+1 to show the project tree

**Expected Behavior**

**Environment**
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to Daniel Ramos
Subscription is active until January 17, 2024.
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.vermouthx.idea (1.14.3)
    com.github.copilot (1.2.6.2594)
    commit-prefix-plugin (1.2.1)
    com.jetbrains.jax.ws (231.8109.90)
    org.asciidoctor.intellij.asciidoc (0.38.13)
    com.intellij.lang.jsgraphql (4.0.1)
    com.intellij.bigdatatools (231.9011.34)
    com.mallowigi (90.0.0)
    com.intellij.spring.websocket (231.8770.17)

Kotlin: 231-1.8.21-IJ9011.34

**Comment by mallowigi** [comment]
Will be available next version

**Comment by DanielRamosAcosta** [comment]
Which version @mallowigi? just to keep an eye and start using the plugin again :)
