### ISSUE TITLE
Bug with ts files in webstorm 2023.1 with new UI

### ISSUE THREAD

**Issue by NeAleshka** [mallowigi/a-file-icon-idea#372]
**Describe the bug**
Files with ts extension are assorted with test.ts in webstorm v.2023.1 with new UI.

**To Reproduce**
1.Enable new UI in webstorm versin 2023.1
2.Create example.ts file and create example.test.ts file
3.example.ts and example.test.ts files have identical icon

**Expected Behavior**
example.ts have typeScript.svg and example.test.ts have testts.svg

**Environment**
WebStorm 2023.1.2
Build #WS-231.9011.35, built on May 16, 2023
Licensed to signup scooter
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jinsihou.react.snippets (1.1.1)
    com.mallowigi (90.0.0)
    intellij-extract-css (1.1.231)
    com.github.dinbtechit.vscodetheme (1.8.0)

Plugin version
90.0.0

**Screenshots**

![Screenshot 2023-06-04 214039](https://github.com/mallowigi/a-file-icon-idea/assets/83368735/2645470a-e74f-4f63-a7ad-30732acf6a93)

**Comment by mallowigi** [comment]
Depends where your file is located. If a parent folder is tests or specs, then all typescript files inside have the test icon

**Comment by NeAleshka** [comment]
> Depends where your file is located. If a parent folder is tests or specs, then all typescript files inside have the test icon

Parent folders don`t consist test or spec and if disabled new UI it work correct, i think this bug with new UI
![Screenshot 2023-06-04 214039](https://github.com/mallowigi/a-file-icon-idea/assets/83368735/a3ea37ac-e649-47bf-9a58-496067ab34de)

**Comment by mallowigi** [comment]
Nope: 
<img width="247" alt="CleanShot 2023-06-06 at 09 57 21@2x" src="https://github.com/mallowigi/a-file-icon-idea/assets/5015756/2a782ffa-911f-4123-966a-2a55b297d029">

Can you provide a screenshot of your project tree?
