### ISSUE TITLE
Not working anymore with IntelliJ IDEA 2023.1.1 & 2.23.1.2

### ISSUE THREAD

**Issue by BenjD90** [mallowigi/a-file-icon-idea#373]
# Describe the bug
The icons appear during the startup loading then disapear in files tree and editor tabs. Files and folders are conserned.

**To Reproduce**

1. Install extension Atom Material File Icons
2. Restart IntelliJ
3. Look for the icons

# Expected Behavior

Icons should stay visible.

# Environment
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to ----
Subscription is active until June 13, 2023.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-150-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    run.anything.use.pty=false
    debugger.new.tool.window.layout=true
    project.tree.structure.show.url=false
    search.everywhere.settings=true
    ide.tooltip.initialDelay=0
    ide.experimental.ui=true
    ide.images.show.chessboard=true
    js.debugger.webconsole=false

Non-Bundled Plugins:
    org.jetbrains.plugins.go-template (231.8109.91)
    com.khmelyuk.multirun (1.13)
    de.ehmkah.projects.imgdiff (1.11.0)
    Scratch (1.10)
    com.dubreuia (2.6.0)
    String Manipulation (9.7.1)
    co.bito.bito-intellij (1.0.138)
    org.turbanov.commits.message.checker (1.2)
    krasa.IdeaIconPack (1.14)
    net.ashald.envfile (3.4.1)
    com.intellij.kubernetes (231.9011.4)
    net.seesharpsoft.intellij.plugins.csv (3.2.0-231)
    ru.adelf.idea.dotenv (2023.1)
    com.mallowigi (90.0.0)
    uk.co.ben-gibson.remote.repository.mapper (4.3.2)
    zielu.gittoolbox (500.0.10+213)
    org.sonarlint.idea (8.3.0.71062)
    com.dt.theme.vs (1.0)

Kotlin: 231-1.8.21-IJ9011.34
Current Desktop: X-Cinnamon

# Screenshots
![image](https://github.com/mallowigi/a-file-icon-idea/assets/8216338/2b04419b-5608-4cac-91e7-0eeef46e21c9)
![Peek 2023-06-08 19-05](https://github.com/mallowigi/a-file-icon-idea/assets/8216338/63d46ca0-b026-4816-9553-3efc15fac130)

**Comment by mallowigi** [comment]
Didn't you activate the "Hidden file icons" by mistake? I'm using this plugin every day, I would have known if it stopped working.

**Comment by BenjD90** [comment]
@mallowigi Thanks a lot it was that, so simple when you know it !

My new conf is that : 

![image](https://github.com/mallowigi/a-file-icon-idea/assets/8216338/2fbad441-b298-435a-b841-579d54ecc22c)

I discovered this menu with the upgrade, then i thought that "Hidden file icons" was to add icons to hidden files :confused:
