### ISSUE TITLE
Crashes Idea on v91.0 update

### ISSUE THREAD

**Issue by DocAmaroo** [mallowigi/a-file-icon-idea#374]
**Describe the bug**

I upgraded my plugin from v90.0 to v91.0 and then on restart Webstorm couldn't load correctly.

Here is how I feel it happens:
1. The Idea starts.
2. The plugin tries to change icon files but something cannot be rendered.
3. The Idea start to freeze (see screenshot below).

From there, the window cannot be closed without killing the process.

I'm sure this comes from this plugin because:
- It's the only one I updated and it start to bug on restart.
- When I remove the plugin folder manually from the JetBrain directory (`~/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/231.9011.35.plugins`) the Idea start normally.
- I tried to reinstall, but the same thing happened.

**To Reproduce**

1. Install version `v90.0`
2. Update to `v91.0`
3. Restart Webstorm

**Expected Behavior**

The Idea should start without crashing.

**Environment**

Note: The Atom Material Icon is not in the plugin list because I can't interact with the window when installed.

```
WebStorm 2023.1.2
Build #WS-231.9011.35, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.6-76060206-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 16
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.new.tool.window.layout=true
    documentation.show.toolbar=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    manjaro.ptpb (1.6)
    club.nutsoft.Github3Theme (1.2.0)
    com.github.nicsilver.jumpertest (0.1.4)
    com.villains.intelij.plugin.newoceantheme (1.2.2)
    commit-template-idea-plugin (1.2.0)
    io.github.anvell.dune-theme (2.0.4)
    quokka.js (1.0.388)
    com.intellij.properties (231.8770.3)
    com.eversql.plugins.jetbrains (1.3.1)
    color.scheme.GitHub 3 (1.2.1)
    ru.adelf.idea.dotenv (2023.1)
    zielu.gittoolbox (500.0.10+213)
    izhangzhihao.rainbow.brackets (2023.2.11)

Current Desktop: pop:GNOME
```

**Screenshots**

![image](https://github.com/mallowigi/a-file-icon-idea/assets/56256989/470aa83c-afc8-4ed8-af3a-fdb133041af9)

**Comment by agileago** [comment]
+1

**Comment by majkelch** [comment]
Can confirm, IDE freezes with very high CPU load.

**Comment by JohnnyDevNull** [comment]
Same with WebStorm, i've downgraded manually to 90.0.0
