### ISSUE TITLE
Custom associations

### ISSUE THREAD

**Issue by AliYusuf95** [mallowigi/a-file-icon-idea#38]
Is there any way to add custom associations? I want to add icons to some of my directories and files that are not listed in the [folder associations](https://github.com/mallowigi/a-file-icon-idea/blob/master/src/main/resources/folder_associations.xml) and [icon associations](https://github.com/mallowigi/a-file-icon-idea/blob/master/src/main/resources/icon_associations.xml) lists.

**Comment by LucaSoato** [comment]
Yeah, it would be so cool to add custom association.

**Comment by PHPadawan** [comment]
+1

**Comment by joaodarocha** [comment]
This would be awesome!

**Comment by mallowigi** [comment]
Yes I saw. They are using project files to add custom associations, but I'm developing an UI to do this from the IDE (and it's painful).

It's in the last steps, bear with me!

**Comment by joaodarocha** [comment]
I can see that it's merged now, but I can only install the version 17.0 on PyCharm. 

Do you know how long it takes (in average) for JetBrains to review the plugin update?

**Comment by mallowigi** [comment]
If you have 17.0 it means that you're still on 2019. I don't plan to release updates for deprecated versions so I suggest you update to 2020.

**Comment by AliYusuf95** [comment]
@mallowigi Can we select from the plugin icons?

**Comment by mallowigi** [comment]
Per project configuration is planned for a future version. As for the plugin icons, this is a good idea, but kind of hard to implement. Because the icons are bundled inside the jar, you can't really select them from the file system. 

I'll try to work on this in a future release but this is pretty hard.

You can also clone this project https://github.com/mallowigi/iconGenerator and use icons from there.

**Comment by AliYusuf95** [comment]
@mallowigi Even just a dropdown and selecting the icons? 
It a long time since I used Java and Kotlen but I'll try to make PR.

**Comment by mallowigi** [comment]
Again, the icons are from the jar, so I had a lot of issues with it. If you can manage to do it, that would be great.

**Comment by mallowigi** [comment]
Again, the icons are from the jar, so I had a lot of issues with it. If you can manage to do it, that would be great.
