### ISSUE TITLE
Error in this plugin when opening intellij idea 2023.2

### ISSUE THREAD

**Issue by williamfonseca13** [mallowigi/a-file-icon-idea#392]
**Describe the bug**
After updating to intelij idea 2023.2 this error started to appear.

**To Reproduce**
Update intellij to version 2023.2

**Environment**
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    compiler.automake.postpone.when.idle.less.than=2000
    debugger.new.tool.window.layout=true
    compiler.document.save.enabled=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.tabnine.TabNine (1.0.36)
    mobi.hsz.idea.gitignore (4.5.1)
    CMD Support (1.0.5)
    com.intellij.properties.bundle.editor (232.8660.88)
    PMDPlugin (1.8.27)
    org.jetbrains.plugins.docker.gateway (232.8660.202)
    com.mallowigi (91.0.0)
    com.nasller.CodeGlancePro (1.6.7)
    Batch Scripts Support (1.0.13)
    String Manipulation (9.10.0)
    com.jetbrains.jax.ws (232.8660.142)
    GsonOrXmlFormat (2.0)
    org.sonarlint.idea (8.4.0.73538)
    ch.newinstance.plugin.mavendependencychecker (1.8.1)
    MavenRunHelper (4.23.222.2964.0)
    org.asciidoctor.intellij.asciidoc (0.38.20)
    com.bruce.intellijplugin.generatesetter (2.8.3)
    com.nvinayshetty.DTOnator (V0.997)
    com.haulmont.jpab (2023.3.1-232)
    izhangzhihao.rainbow.brackets (2023.3.2)

Kotlin: 232-1.9.0-IJ8660.185

[Plugin error StackTrace.txt](https://github.com/mallowigi/a-file-icon-idea/files/12197177/Plugin.error.StackTrace.txt)

**Comment by mallowigi** [comment]
Duplicate
