### ISSUE TITLE
Modifying some icon colors does not seem to take effect.

### ISSUE THREAD

**Issue by tinyRipple** [mallowigi/a-file-icon-idea#402]
**Describe the bug**

When I try to change the `.npmrc` icon color, but it takes no effect.

**To Reproduce**

1. Change the `.npmrc` icon color to `#D14748`
2. The icon color keeps the default `green` (may be it is green)

**Expected Behavior**

Change the icon `.npmrc` to color `#D14748`

**Environment**

* Mac
* WebStorm 2023.2
* Atom Material Icons 92.0.0
* list of enabled plugins: 1. Atom Material Icons 2. Material Theme UI 3. Github Copilot

**Screenshots**

<img width="1167" alt="image" src="https://github.com/mallowigi/a-file-icon-idea/assets/69381867/738063b7-ae4c-4205-8dba-b3c47a2b3a9a">
<img width="369" alt="image" src="https://github.com/mallowigi/a-file-icon-idea/assets/69381867/93ada891-f50e-4ea9-a4ef-555f39c04ba7">

**Comment by mallowigi** [comment]
Thanks. There are some icons with the wrong path, I did a quick search to see if there are others in that case.

It will be fixed next release

**Comment by tinyRipple** [comment]
Thank you so much!
