### ISSUE TITLE
file icon setting reverted for java files

### ISSUE THREAD

**Issue by rlnt** [mallowigi/a-file-icon-idea#407]
**Describe the bug**
For some reason, I think the file icon setting is reverted for Java files. As you can see in my video, all Java files are shown with the Java logo. When I disable the file icons, they will appear in the style of the atom material style except for the `package-info.java` files. Packages and other file types seem to work fine if the setting is enabled.

https://github.com/mallowigi/a-file-icon-idea/assets/16513358/c1aa9b68-c5fd-435a-810f-a19fbf1b4f91

**To Reproduce**
1. Open a Java project
2. See that the icons are not correct
3. Open quick actions (double shift) and type `icons` and toggle the setting `File Icons`

**Expected Behavior**
The Java file icons should be in the atom material style when the setting is enabled.

**Environment**
```
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    debugger.mayBringFrameToFrontOnBreakpoint=false
    run.processes.with.pty=false
    ide.experimental.ui=true
    ide.balloon.shadow.size=15

Non-Bundled Plugins:
    com.vecheslav.darculaDarkerTheme (1.2.0)
    Statistic (4.2.7)
    com.github.copilot (1.2.21.2995)
    org.jetbrains.jumpToLine (0.1.13)
    org.jetbrains.plugins.hocon (2023.1.0)
    manifold.ij (2023.1.15)
    color.scheme.Relentless-Colors (1.2.4)
    com.nasller.CodeGlancePro (1.7.4)
    com.intellij.plugins.vscodekeymap (232.8660.88)
    com.samdark.intellij-visual-studio-code-dark-plus (2.8)
    ski.chrzanow.foldableprojectview (1.1.6)
    com.chylex.intellij.inspectionlens (1.3.0)
    com.dsoftware.ghtoolbar (1.13.3)
    izhangzhihao.rainbow.brackets (2023.3.3)
    net.labymod.intellij.singlehotswap (2.6)
    me.shedaniel.architectury (1.6.3)
    com.mallowigi (93.0.1)
    mobi.hsz.idea.gitignore (4.5.1)

Kotlin: 232-1.9.0-IJ8660.185
```

**Comment by mallowigi** [comment]
[Atom Material Icons-93.0.2.zip](https://github.com/mallowigi/a-file-icon-idea/files/12419110/Atom.Material.Icons-93.0.2.zip)

You're right. I didn't test it well. I reverted to the previous implementation. Sorry.

I will release a new version next week because I don't want to add more burden to the users.

**Comment by Hondatron5000** [comment]
I'm using 93.1.0 and this problem is still present. What version should this be fixed in?

**Comment by mallowigi** [comment]
It should be fixed. You still don't see it? Are you sure you have the PSI icons setting turned on?
