### ISSUE TITLE
icon path - mysql

### ISSUE THREAD

**Issue by WeellingtonCesa** [mallowigi/a-file-icon-idea#41]
Please can you replicate the same sql icon to a **mysql** folder?

**Comment by mallowigi** [comment]
Sure, but I’d suggest you to do a pull request instead. Thanks!

**Comment by WeellingtonCesa** [comment]
You say follow up, correct? By **Watch**?

**Comment by WeellingtonCesa** [comment]
And ... ?

**Comment by mallowigi** [comment]
I'll do it for version 20.0

**Comment by WeellingtonCesa** [comment]
OK, thank you
