### ISSUE TITLE
Can the PSI icon be switched according to different UI?

### ISSUE THREAD

**Issue by dcsmf** [mallowigi/a-file-icon-idea#413]
When I turn off the PSI icon ![Snipaste_2023-09-27_14-18-33](https://github.com/mallowigi/a-file-icon-idea/assets/10435048/43ffc7d9-bb50-40bd-a9a1-b97327061ac9) , it will start from ![Snipaste_2023-09-27_14-18-59](https://github.com/mallowigi/a-file-icon-idea/assets/10435048/383b18da-8dbb-4a95-a9f6-4882e7c5b63e) Become ![Snipaste_2023-09-27_14-19-13](https://github.com/mallowigi/a-file-icon-idea/assets/10435048/07a2cc39-ff59-4829-8ef0-b496b60726a9).

This is normal in the classic UI, but I'm using the new UI, which is weird.

I wonder if IDEA has a limitation on plugins that causes this?

If possible, PSI icons can be disabled and reverted to the corresponding icons according to different UIs.

If the plugin can't tell which UI it is, can it give the user the choice of which one to revert to?

**Comment by mallowigi** [comment]
This will be available next release
