### ISSUE TITLE
Package/folder visualization affected by Atom Icon Plugin

### ISSUE THREAD

**Issue by lhleonardo** [mallowigi/a-file-icon-idea#416]
**Describe the bug**
The IntelliJ tree appearance is not working well when Atom Icons is enabled. I've tried tests activating and deactivating the "Enable Folder Icons" option. In this case, the IDE shows a full package path "inside" a package, which presents a wrong structure folder. I've attached screenshots that show the bug.

**To Reproduce**
1. Install the Atom Plugin
2. Activate the flag "Enable Folder Icons"
3. check a package

**Expected Behavior**
The package visualization structure is expected not to be affected by the Atom Icon Plugin.

**Environment**
IntelliJ IDEA 2023.2.2 (Community Edition)
Build #IC-232.9921.47, built on September 12, 2023
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.vecheslav.darculaDarkerTheme (1.2.0)
    org.zalando.intellij.swagger (1.2.0)
    krasa.CpuUsageIndicator (1.17.2023)
    com.berzanmikaili.intellij.monokai_pro (2.0.2c)
    com.thvardhan.gradianto (5.4)
    Docker (232.9921.55)
    Lombook Plugin (232.9921.47)
    String Manipulation (9.11.3)
    com.intellij.lang.jsgraphql (4.0.2)
    dev.flikas.idea.spring.boot.assistant.plugin (222.17.2)
    izhangzhihao.rainbow.brackets (2023.3.6)
    org.mapstruct.intellij (1.6.1)
    com.haulmont.jpab (2023.3.5-232)
    com.almightyalpaca.intellij.plugins.discord (1.11.0)
    com.mallowigi (93.1.0)
    zielu.gittoolbox (500.0.21+222)
    mobi.hsz.idea.gitignore (4.5.1)
    org.sonarlint.idea (9.0.0.75308)
    MavenRunHelper (4.26.0-IJ2022.2)

Kotlin: 232-1.9.0-IJ9921.47

**Screenshots**
![Image 1 - "Enable Folder Icons" unchecked](https://github.com/mallowigi/a-file-icon-idea/assets/11544276/8abefbd8-4934-4fd5-80ff-d5ccdfeda4d7)
![Image 2 - "Enable Folder Icons" checked](https://github.com/mallowigi/a-file-icon-idea/assets/11544276/c63e3309-5fe2-409f-b3c7-43e46bdcf91e)

**Comment by mallowigi** [comment]
I have no idea on how to fix that and how the plugin is related. Can you provide an example repository where this happens? I've been using this plugin for who knows how long and haven't encountered that.

**Comment by mallowigi** [comment]
Closing due to lack of response
