### ISSUE TITLE
Add SQLite Icon to the pack

### ISSUE THREAD

**Issue by DeathGOD7** [mallowigi/a-file-icon-idea#422]
**Is your feature request related to a problem? Please describe.**
No, it's related to the icon.

**Describe the solution you'd like**
I would like to request you to add an SQLite icon to the pack (mainly in folder as *.sqlite3 file already shows the icon)

**Describe alternatives you've considered**
-

**Additional context**
![256px-Sqlite-square-icon svg](https://github.com/mallowigi/a-file-icon-idea/assets/36422471/f3ab6672-e400-4cf7-b8b5-c697790ca21c)
[Source: SQLite Icon](https://commons.wikimedia.org/wiki/File:Sqlite-square-icon.svg)

**Comment by mallowigi** [comment]
There is already a sqlite icon as far as i remember. If an extension is missing, please open a PR.
