### ISSUE TITLE
ESLint.config.js file showing the wrong icon

### ISSUE THREAD

**Issue by JamiesonRoberts** [mallowigi/a-file-icon-idea#429]
**Describe the bug**
ESLint's new flat config files are now displaying the correct icon

**To Reproduce**
create a file with the filename of `eslint.config.js` and see that the icon is a JS icon instead of ESLint

**Expected Behavior**
It should show the ESLint icon

**Environment**
IntelliJ PHPStorm on Mac M1 - plugin version 93.1.0

**Comment by JamiesonRoberts** [comment]
As a follow up to this, it should be fairly easy to fix. I copied the syntax for prettier and tweaked for ESLint and it worked

`^(\.eslint|eslint\.config)(\.[cm]?js|ts|json|ya?ml)?$` appears to work

**Comment by mallowigi** [comment]
you can open a PR if you want

**Comment by JamiesonRoberts** [comment]
@mallowigi I would love to, however I've never worked with a project in this language. Can you point me in the right direction where I can make that change?

**Comment by mallowigi** [comment]
https://github.com/mallowigi/iconGenerator

You need to add it to `icon_associations.xml` (or `folder_associations` for folders)
