### ISSUE TITLE
Some icons are too "heavy"

### ISSUE THREAD

**Issue by lllopo** [mallowigi/a-file-icon-idea#43]
The .js and bootstrap icons are too "heavy" compared to others. By "heavy I men they have too much color filled areas compared to all other icons.

**Comment by lllopo** [comment]
Don't get me wrong, the icon as a whole is ok and everything, but because of the big area of flat bright color it looks visually bigger than the others. Reducing it by a pixel in each direction would look more balanced with the others, I think. Like this :

![Untitled](https://user-images.githubusercontent.com/5485902/70860798-e4743880-1f2e-11ea-8d98-6b63c4bdc78a.png)

Look at the "build-config.js" icon - i modified it to be a bit smaller (actually it is just as wide as the "package.json" icon) and it looks more balanced and not so ... errm ... imposing to me.

**Comment by mallowigi** [comment]
ok
