### ISSUE TITLE
Icons Don't Render On Large Files

### ISSUE THREAD

**Issue by AbbasSrour** [mallowigi/a-file-icon-idea#435]
**Describe the bug**
When opening large in a  JetBrains IDEs (Pycharm, Webstorm, Goland)  with this plugin all the icons either don't render while not clicked, or the rendered is mangled, when restarting the IDE everything goes back to normal.

**To Reproduce**
1. Open a huge file.

**Expected Behavior**
The icons appear properly.

**Environment**
PyCharm 2023.3.2 (Professional Edition)
Build #PY-233.13135.95, built on December 19, 2023
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.6.10-zen1-1-zen
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  solarized (1.5)
  com.nasller.CodeGlancePro (1.7.8)
  IdeaVIM (2.7.5)
  com.github.copilot (1.4.8.4188)
  com.intellij.ideolog (222.2.0.0)
  com.markskelton.one-dark-theme (5.9.0)
  com.tylerthrailkill.intellij.solarized (3.0.0)
  com.alex.tokyonight (0.1.6)
  com.wakatime.intellij.plugin (14.3.8)
  com.intellij.grazie.pro (0.3.271)
  com.intellij.ml.llm (233.13135.116)
  io.k6.ide.plugin (0.3.0)
  com.intellij.tide (233.13135.116)
  ru.adelf.idea.dotenv (2023.3)
  org.tonybaloney.security.pycharm-security (1.29.0)
  com.intellij.bigdatatools.core (233.13135.103)
  mobi.hsz.idea.gitignore (4.5.2)
  com.google.gct.core (23.12.3-api-version-223)
  aws.toolkit (2.4-233)
Current Desktop: Hyprland (It doesn't also work on gnome)

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version
* If needed a list of enabled plugins -->

**Screenshots**

**Comment by mallowigi** [comment]
Can you provide an example repository?
