### ISSUE TITLE
Add Some Icon For This  Folder Names List (in description ) Pleeeeeeeeeeeeeeeeeeeeeeeeeeeeeas

### ISSUE THREAD

**Issue by mo-albosifi** [mallowigi/a-file-icon-idea#438]
Manager 
Management
Consumer
Behavior
Localization
Configurations
Interceptors
Db (database)
Identity
Real 
Installers
Others
Projections
Reflection
Response
Optimistic
Concurrency
Ids
Serialization
BackgroundWorkers
Aggregates

**Comment by mallowigi** [comment]
I wouldn't know what icons to add. If you want to provide new association please fork https://github.com/mallowigi/iconGenerator and add new Icons
