### ISSUE TITLE
Vue icon

### ISSUE THREAD

**Issue by lllopo** [mallowigi/a-file-icon-idea#44]
I'd rather say the original Vue files icon (that is also the original vue logo) is far better looking. Is there any copyright reason to not use it here too ?

**Comment by mallowigi** [comment]
This is the concept of these icons. What exactly do you mean?

**Comment by lllopo** [comment]
Don't get me wrong, the icon as a whole is ok and everything, but because of the big area of flat bright color it looks visually bigger than the others. Reducing it by a pixel in each direction would look more balanced with the others, I think. Like this :

![Untitled](https://user-images.githubusercontent.com/5485902/70860652-d58c8680-1f2c-11ea-916f-6bfab6f90be1.png)

Look at the "build-config.js" icon - i modified it to be a bit smaller (actually it is just as wide as the "package.json" icon) and it looks more balanced and not so ... errm ... imposing to me.

**Comment by lllopo** [comment]
Well ... what it is - left, what I think it should be - right :

![Untitled1](https://user-images.githubusercontent.com/5485902/70860780-bbec3e80-1f2e-11ea-99ad-0f4d9d21a676.png)

**Comment by mallowigi** [comment]
Depends on what it is in the original file-icons package. If it’s like this, so it should be.

--
Elior

**Comment by lllopo** [comment]
So you don't modify the icons by yourself .. I see ... you can close this, then, since it is not in your hands to change it.

**Comment by mallowigi** [comment]
No you don’t understand, I can change them, but the source of the icons is from the package. If they are like that there, so they should be like that here. It’s for the sake of consistency.

If you think that the color could be changed, tell me.

--
Elior

**Comment by lllopo** [comment]
Yes, I think it should be changed as this is the original Vue.js logo. You can check for yourself here : [https://vuejs.org/](https://vuejs.org/)
