### ISSUE TITLE
How to customize the button color and icon color here?

### ISSUE THREAD

**Issue by tlerbao** [mallowigi/a-file-icon-idea#447]
<img width="556" alt="CleanShot 2024-04-22 at 10 56 17@2x" src="https://github.com/mallowigi/a-file-icon-idea/assets/20442232/44e52264-3e06-4bf7-80b9-90f2796e5a23">

As shown in the figure, how to customize the colors of the run and stop buttons in the upper right corner, including the icon colors.

Below is the appearance of the disabled UI Icon.

<img width="517" alt="CleanShot 2024-04-22 at 10 57 43@2x" src="https://github.com/mallowigi/a-file-icon-idea/assets/20442232/ea994740-a211-4dfd-b421-3273651ad64a">

**Comment by mallowigi** [comment]
It's not possible out of the box. It's something coming out of the theme itself.

Perhaps in a future update I'll add a setting to override the themes' color

**Comment by tlerbao** [comment]
好想法，这个设置应该添加，感谢开源。
