### ISSUE TITLE
.java icon not showing, only some weird cube

### ISSUE THREAD

**Issue by axtrough** [mallowigi/a-file-icon-idea#455]
I am not sure what this is but why are my .java files this cube instead of the java icon?
![Screenshot_1](https://github.com/mallowigi/a-file-icon-idea/assets/77877788/144c4115-2bdf-4eb8-8a73-03dcc1b63465)

**Comment by mallowigi** [comment]
These are PSI icons. There are icons representing the type of file (class, interface, enums)...
