### ISSUE TITLE
Missing PHP file icon

### ISSUE THREAD

**Issue by amstiel** [mallowigi/a-file-icon-idea#46]
I noticed that PHP files used standard icon instead of Material one. 
See screenshot below:

![php_file_icon2](https://user-images.githubusercontent.com/9428948/71177974-e9334680-22b8-11ea-9b7c-8c8257cbe1bf.png)

My Atom Material Icons config:

![php_file_icon3](https://user-images.githubusercontent.com/9428948/71178004-f6503580-22b8-11ea-98b8-2fa1f0906b44.png)

In plugin's sources I found PHP file association string, but it's commented out:

![php_file_icon](https://user-images.githubusercontent.com/9428948/71178147-429b7580-22b9-11ea-9109-5897c4aa302e.png)

I suppose this has something to do with the UI Icons ("Enable UI Icons" option).

**Comment by mallowigi** [comment]
Yes, PHP icons are different because they use UI icons to change their icons, instead of the regular psi icons. Uncommenting the line would cause all PHP files to have the elephpant, thus not being able to distinguish between regular PHP files and files with classes/traits/etc...
