### ISSUE TITLE
Arrows are black after IDE restart

### ISSUE THREAD

**Issue by bartekczyz** [mallowigi/a-file-icon-idea#49]
All arrows in project structure are black even though they were light grey after installing the plugin. When I change the theme to something and back to Darcula - it works again, but when I close and open my IDE, they become black. I've also tried uninstalling the plugin and installing again - it works after fresh install, but again - breaks after restart.

![arrows](https://user-images.githubusercontent.com/24492356/75521629-6e994c80-5a08-11ea-8c9a-85331e62e57f.png)

IDE: IJ 2020.1 EAP
System: MBP MacOS 10.15.3
Theme: Darcula

**Comment by exocom** [comment]
@mallowigi Looks like the TintedIconsComponent is using the Label.infoForeground as the themedColor. When using Dracula this is a very dark and makes the icons hard to see.

Without understanding how this fully works, here are some ideas.

1. Loading a 3rd color "TextField.caretForeground" as treeIconColor. Then use that dynamically instead of themedColor when the icon being loaded is a tree icon.
2. Use "TextField.caretForeground" instead of "DefaultTabs.underlineColor" for themedColor. See below. (Might mess up other icons)

`java/com/mallowigi/icons/TintedIconsComponent.java`

```java
private static ColorUIResource getThemedColor() {
    return new ColorUIResource(JBColor.namedColor("TextField.caretForeground", UIUtil.getContextHelpForeground()));
}
```

**Comment by byyxx128** [comment]
Not only arrows, but also some strings. e.g. descriptions in Marketplace.

Before using:
![image](https://user-images.githubusercontent.com/20079289/77622309-02fbbe00-6f79-11ea-83ae-5668fcac7141.png)

After using:
![image](https://user-images.githubusercontent.com/20079289/77622336-0f801680-6f79-11ea-93da-7887de11ca8c.png)

P.S. Please always restart your IDE to make it effective after enabling/disabling the plugin.

**Comment by byyxx128** [comment]
Not only arrows, but also some strings. e.g. descriptions in Marketplace.

### **Before using:**
![image](https://user-images.githubusercontent.com/20079289/77622309-02fbbe00-6f79-11ea-83ae-5668fcac7141.png)

### **After using:**
![image](https://user-images.githubusercontent.com/20079289/77622336-0f801680-6f79-11ea-93da-7887de11ca8c.png)

P.S. Please **always restart** your IDE to make it effective after enabling/disabling the plugin.

**Comment by byyxx128** [comment]
Not only arrows, but also some strings. e.g. descriptions in Marketplace.

### **Before using:**
![image](https://user-images.githubusercontent.com/20079289/77622309-02fbbe00-6f79-11ea-83ae-5668fcac7141.png)

### **After using:**
![image](https://user-images.githubusercontent.com/20079289/77622336-0f801680-6f79-11ea-93da-7887de11ca8c.png)
![image](https://user-images.githubusercontent.com/20079289/77638923-e53b5280-6f92-11ea-9934-9cdb21a55ce6.png)

_P.S. Please **always restart** your IDE to make it effective after enabling/disabling the plugin._

**Comment by bartekczyz** [comment]
Fixed https://github.com/mallowigi/a-file-icon-idea/releases/tag/v21.0
