### ISSUE TITLE
Icons are missing.

### ISSUE THREAD

**Issue by Kamieniu** [mallowigi/a-file-icon-idea#52]
WebStorm 2020.1
Build #WS-201.6668.106, built on April 6, 2020
Licensed to Gentleman's Code Franciszek Stodulski
Subscription is active until November 15, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: suggest.all.run.configurations.from.context=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: zielu.gittoolbox, com.chrisrm.idea.MaterialThemeUI, github.cweijan.test-theme, Dart, izhangzhihao.rainbow.brackets, com.intellij.lang.jsgraphql, quokka.js, com.mallowigi

![image](https://user-images.githubusercontent.com/14015728/78709427-ef0a7180-7913-11ea-9a8b-2d6368daa7e7.png)

There are no icons after updating WebStorm to the latest version.

**Comment by Kamieniu** [comment]
After installation, they were visible, but after closing Preferences window, they disappeared

**Comment by mallowigi** [comment]
Make sure you don't have the "Hide File Icons" option selected

**Comment by Kamieniu** [comment]
@mallowigi 
YEAH! That was it! 
I think, this option shouldn't be by default turned ON 

GREAT JOB! 
Love these icons
