### ISSUE TITLE
Icon Request: Scheduler / Cron jobs

### ISSUE THREAD

**Issue by devansh08** [mallowigi/a-file-icon-idea#55]
Icon for package (thinking in terms of Java) that has scheduler or cron job related files or classes. Maybe something with a tiny clock or something like that ? :smile:

**Comment by mallowigi** [comment]
It depends, what is such an extension for that?

**Comment by devansh08** [comment]
So thinking in terms of Java (Spring more specifically), I was assuming an icon can be associated to the name of the folder (Pls correct me if this isnt how the icons work). Kinda like how the "controllers", "db" and "security" folders have an icon for them.
