### ISSUE TITLE
Class, Interface, Trait are same

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [mallowigi/a-file-icon-idea#57]
Before we can differentiate the file by seeing their icons

![details](https://user-images.githubusercontent.com/48278861/79268649-ee964b80-7ebc-11ea-9dff-3e540bc347ff.PNG)

But now all are the same

![deails2](https://user-images.githubusercontent.com/48278861/79268697-0241b200-7ebd-11ea-86a6-619e03515e90.PNG)

phpstorm version 2020.1

**Comment by mallowigi** [comment]
Just released an hotfix now. Thanks
