### ISSUE TITLE
.cpp and .hpp use the same icon, and it's hard to differentiate at a glance

### ISSUE THREAD

**Issue by Twinki14** [mallowigi/a-file-icon-idea#58]
Primarily programming with C++ projects, and I mainly used the Material Theme plugin for CLion before the icon support was removed from the plugin in favor of using this plugin as a replacement, which is all well in good [except that .cpp and .hpp use the same icon, with no color difference](https://i.imgur.com/DtRlinU.png)

Replacing the .hpp icon with the .h icon would be an easy solution, I believe that's how it was before in the larger Material Theme plugin

Using 22.0 in the above screen, on CLion 2020.1

**Comment by mallowigi** [comment]
I think it's a bug, it should be the same icon as hxx

I'll fix it
