### ISSUE TITLE
Icons are not changed in git > local changes (PhpStorm 2020.1)

### ISSUE THREAD

**Issue by Vsevo1od** [mallowigi/a-file-icon-idea#59]
Icons are applied everywhere but "local changes" tab.
I tried reinstalling the plugin, restarting IDE, invalidating caches

PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020

Also the same issue is in Idea 2020.1

![image](https://user-images.githubusercontent.com/5249361/79329101-d9063d80-7f1f-11ea-8798-9d2b47c43a96.png)

**Comment by mallowigi** [comment]
What version are you on?

**Comment by Vsevo1od** [comment]
22.1

**Comment by mallowigi** [comment]
just checked, should work in next version
