### ISSUE TITLE
Redux Epic

### ISSUE THREAD

**Issue by JalilArfaoui** [mallowigi/a-file-icon-idea#61]
Since we now have a `Redux Saga` icon, maybe we could complete the `Redux` icon with an `Epic` icon …

Either based on `Redux ones`, with another color (pink ?), or based on the official logo of Redux Observable :  https://redux-observable.js.org/

If a file ends with `\.epics?\.[tj]s`

Thanks !

**Comment by mallowigi** [comment]
done
