### ISSUE TITLE
 some icons are more difficult to distinguish

### ISSUE THREAD

**Issue by hua03** [mallowigi/a-file-icon-idea#62]
After upgrading IDEA 2020.1.1 EAP,  the icon of h5 and the icon of js look so similar that sometimes it is more difficult to distinguish .like this:
![image](https://user-images.githubusercontent.com/19561959/80068155-b4d6dc00-8571-11ea-91cd-c04403a0140a.png)

And in IDEA 2019.3, it's:
![image](https://user-images.githubusercontent.com/19561959/80068735-b0f78980-8572-11ea-9006-58a49cfb3679.png)

**Comment by mallowigi** [comment]
Not planning to change it at the moment. Please wait until the custom file associations is finished.
