### ISSUE TITLE
Selected directory icon barely visible

### ISSUE THREAD

**Issue by pkruithof** [mallowigi/a-file-icon-idea#65]
Hi, I'm not sure if this is the right place to raise this issue, but here goes:

The icon for a selected directory seems to get a different color, which is barely visible against the highlight color:

Not selected:

![image](https://user-images.githubusercontent.com/330828/80588035-e0494300-8a17-11ea-87e8-71bdd1863060.png)

Selected:

![image](https://user-images.githubusercontent.com/330828/80587999-d32c5400-8a17-11ea-87c5-9f8817827fd1.png)

Selected, but not active window:

![image](https://user-images.githubusercontent.com/330828/80588081-f0f9b900-8a17-11ea-8f78-4290ad4f1e11.png)

I've tried all arrow styles, but they all have this problem. I'm using the Material Theme in combination with Darcula.

**Comment by mallowigi** [comment]
Hmmm... The arrows are taking the color from a theme property that is not always configurable...

I think I'll add a color scheme property to configure this, what do you think?

**Comment by pkruithof** [comment]
What's interesting is that sometimes when I fiddle around with the icon/theme settings, it seems to (re)set some property and the arrow color stays the light grey it normally is. Only it does not stay that way for long. I'm trying to remember if the problem occurs again when I (re)start the IDE, or if it happens more randomly. I'll watch out for it and report back if I can.

In the meantime, is there anything else you need for this?

**Comment by mallowigi** [comment]
I've added a custom accent setting, you can fine tune the color there.

**Comment by pkruithof** [comment]
Works like a charm, thank you!
