### ISSUE TITLE
prisma folder icon not working

### ISSUE THREAD

**Issue by justmelnyc** [mallowigi/a-file-icon-idea#66]
the prisma folder icon is not working, I'm running the latest version

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/81643781-01099380-942f-11ea-87c4-f55e2b54221f.png)
Works fine to me...

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/81643781-01099380-942f-11ea-87c4-f55e2b54221f.png)
Works fine to me...
