### ISSUE TITLE
Change Python Logo

### ISSUE THREAD

**Issue by alexwolf22** [mallowigi/a-file-icon-idea#67]
Hi is there a way to change the python logo back to what PyCharm normally uses?

I love this plugin and all the icons, except the Python one. Like orange really? It's driving me crazy while coding lol

I can fork this repo and do it myself if you can point me in the right direction to how to disable certain icons; not a java guy at all unfortunately. 

I see that Jetbrains had a [whole section](https://www.jetbrains.org/intellij/sdk/docs/basics/basics.html) on developing plugins I could use to get this done. 

Would be a nice feature to add for people to choose which plugins are enabled or not.

**Comment by luokuning** [comment]
Same needs here. This plugin and the icons are outstanding, however, some of the file icons that I would like to enable the default one. If there could an option that user can choose whether to use the default icon would be really nice.

**Comment by alexwolf22** [comment]
@luokuning I came across this [plugin](https://plugins.jetbrains.com/plugin/12416-coderpillr-icons) which has a lot of the atom icons and it is possible to edit them.

Unfortunately I couldn't use it though because it removed the breakpoint icons in PyCharm for me.

**Comment by mallowigi** [comment]
I’m finally working on the custom file associations, though in all honesty I am not sure that will be what you request but it would allow you to override the default ones
