### ISSUE TITLE
Monochrome icons state not persisted after restarting IDE

### ISSUE THREAD

**Issue by golimpio** [mallowigi/a-file-icon-idea#74]
When changing icons to `Monochrome Icons` and click on `Apply`, it works as expected, and I can see the icons changed to monochrome. But after restarting the IDE, the icons are reversed to their colour version again.

The `Monochrome Icons` checkbox option on `Preferences > Appearance & Behavior > Atom Material Icons Settings` is still checked after restarting the IDE.

IDE version:
```
IntelliJ IDEA 2020.1.1 (Community Edition)
Build #IC-201.7223.91, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.mac.show.native.help=true, kotlin.experimental.project.wizard=true
Non-Bundled Plugins: color.scheme.Nord, com.arcticicestudio.nord.jetbrains, org.jetbrains.kotlin, com.mallowigi, io.github.qeesung.component.HighlightBracketPair, BashSupport, org.toml.lang, org.rust.lang
```

Plugin version:
```
24.0
```

OS:
```
macOS Catalina
Version 10.15.4
```

**Comment by JoachimR** [comment]
`uncheck, apply, check, apply `
currently works as a workaround

**Comment by mallowigi** [comment]
Yes, it's a regression bug due by fixing the issue with the weird border at start. Looks like the weird border will be back again.

**Comment by golimpio** [comment]
> `uncheck, apply, check, apply `
> currently works as a workaround

thanks, but the issue is when you restart the IDE, `uncheck, apply, check apply` unfortunately won't work in this case, as soon as you restart the IDE, the icons will revert to colour.

**Comment by NinoFloris** [comment]
>thanks, but the issue is when you restart the IDE, uncheck, apply, check apply unfortunately won't work in this case, as soon as you restart the IDE, the icons will revert to colour.

What he says.

Any reason we can't revert the fix, or at least revert to the old behavior when monochrome is used?

**Comment by mallowigi** [comment]
I am pretty busy at the moment, I can't work on it.

You're free to do PRs
