### ISSUE TITLE
Ability to change folder colour

### ISSUE THREAD

**Issue by NileDaley** [mallowigi/a-file-icon-idea#75]
When using a light theme, the folder colour that is used ( #000000? ) doesn't seem to fit the rest of the icons very well. 

![Screenshot 2020-05-13 at 13 41 23](https://user-images.githubusercontent.com/15862011/81814880-32fb2280-9521-11ea-8271-4e806ca24876.png)

It would be great if there was an option to change the colour, unless this already exists and I don't know how to do it?

**Comment by mallowigi** [comment]
The color should actually be the same color as the text next to it. But I'll add an option to control it in the future, but it's not for right now.
