### ISSUE TITLE
index files has wrong icon

### ISSUE THREAD

**Issue by nimabrownlee** [mallowigi/a-file-icon-idea#78]
Look at how it looks [here](https://i.imgur.com/jCXvFiI.png). No matter javascript or typescript it doesnt show right icon. Whats the fix? This happens on PhpStorm.

**Comment by mallowigi** [comment]
This is a new feature to allow quicker identification of index files. Index files are used a lot in Typescript projects for exporting constants and classes from other files. This adds a layer of differentiation with regular ts/js files

**Comment by nimabrownlee** [comment]
@mallowigi Could you at least make it an option? I rather have normal icons.

**Comment by mallowigi** [comment]
You can add a custom default association

**Comment by nimabrownlee** [comment]
@mallowigi How would you do that? I didn't find anything in the settings.

**Comment by rishabhdeepsingh** [comment]
I am also facing the same error. can you tell me which setting you changed?

**Comment by rishabhdeepsingh** [comment]
Looks like it is fixed now
