### ISSUE TITLE
MyPy icons broken in PyCharm

### ISSUE THREAD

**Issue by Eroppo** [mallowigi/a-file-icon-idea#79]
Hi, thanks for the great plugin!
Some days ago installed [MyPy](https://plugins.jetbrains.com/plugin/11086-mypy) and some of it's icons are broken if Atom Icons is enabled:
![pycharm64_2020-05-26_15-13-10](https://user-images.githubusercontent.com/13285107/82899842-4caa5a00-9f64-11ea-885a-6f267dd6c13b.jpg)
Made some investion and found that it can be repaired by disabling UI Icons in Atom Icons settings, applying, and re-enabling it:
![pycharm64_2020-05-26_15-15-53](https://user-images.githubusercontent.com/13285107/82900172-cc382900-9f64-11ea-9cb0-42e78d1c5d38.jpg)
But after restarting the IDE these icons are dots again...

**Comment by mallowigi** [comment]
hmm yes, this is a recurring issue with external plugins. It happens only with Kotlin, CheckStyle, etc...

I'll keep this open, but I don't have a fix right now.

**Comment by mallowigi** [comment]
I haven't found a great solution for this issue, as there seems to be a race condition between the icons and the toolwindow.

Since I've been stuck for quite a long time, I found a workaround much simpler: an action button to reload the icons manually. That's the best I can do.
