### ISSUE TITLE
Icons froms classes gone after plugin update

### ISSUE THREAD

**Issue by gldrenthe89** [mallowigi/a-file-icon-idea#80]
The light blue 3d like (boxy style) icons are gone on al my classes. they are this light pirple / pink icons wich normally only shown on PHP files wich ar not classes

**Comment by mallowigi** [comment]
lol I always forget to rollback the icon associations for PHP files...

Anyways I'll try to find a fix that doesnt require me to comment stuff.

**Comment by gldrenthe89** [comment]
> lol I always forget to rollback the icon associations for PHP files...
> 
> Anyways I'll try to find a fix that doesnt require me to comment stuff.

Lol. no problem. it is not like a cant work now 😉  I hoped it wasn't a new feature or so 🤣 Glad it isn't

**Comment by cajogos** [comment]
Same issue here, I miss them!! Only changed last night,  that's how good they are and look!
They do improve productivity when working with interfaces, traits, classes, exceptions, etc. in PHP :stuck_out_tongue_closed_eyes: hopefully we can get it back soon :raised_hands:

**Comment by mallowigi** [comment]
Sent an hotfix now. Will be available shortly

**Comment by gldrenthe89** [comment]
Same issue again with latest update
