### ISSUE TITLE
GoLand commit panel not applying Atom Icons

### ISSUE THREAD

**Issue by georgeherby** [mallowigi/a-file-icon-idea#83]
When comparing the file icon for a go file in GoLand 2020.1.2 in the Project panel vs the Commit panel they are different. it looks like the icons are not being applied in the commit panel. Plugin version 25.0

![image](https://user-images.githubusercontent.com/21989833/83002447-fccf9f80-a004-11ea-8059-cca1a20016ce.png)

**Comment by mallowigi** [comment]
That's right. It's one of the subtasks of https://github.com/mallowigi/a-file-icon-idea/issues/68
