### ISSUE TITLE
Version 25.0 Enable PSI Icons has no effect in PhpStorm 2020.1

### ISSUE THREAD

**Issue by alpenist** [mallowigi/a-file-icon-idea#84]
Hello!,
After the last update I've noticed that Class icons wasn't showing the way it used to before.. instead it shows the default ex. pink elephant for .php files, but it's showing correctly when Enable File Icons is unchecked or the plugin is disabled.

Anybody else having the same issue?!

Thanks!

**Comment by mallowigi** [comment]
i've already released an hotfix for this issue, it will be available shortly
