### ISSUE TITLE
.ts (typescript) and .tsx (typescript react) files generate two types of icons. 

### ISSUE THREAD

**Issue by jonolo6** [mallowigi/a-file-icon-idea#85]
My typescript files generate two different icons (see below).

![image](https://user-images.githubusercontent.com/3819396/83074849-3e823980-a049-11ea-9a7d-7eb2e56450b8.png)

Perhaps I have a conflict with some other framework, but looking at my plugins I'm only using `Material Theme UI` as well that impact the UI so I'm not sure what's going on...

**Comment by jonolo6** [comment]
To add this also seems to impact typescript react files (.tsx):

![image](https://user-images.githubusercontent.com/3819396/83075154-c23c2600-a049-11ea-86b3-7c739667b9d4.png)

**Comment by mallowigi** [comment]
Please read the documentation
