### ISSUE TITLE
Custom File Association Icon Not Loading

### ISSUE THREAD

**Issue by alexwolf22** [mallowigi/a-file-icon-idea#88]
Hey love the new update to the plugin! It is great thanks a ton for making things customizable. 

I am trying to update the python file icon using the new `Custom File Associations` but it doesn't seem to be working for me.

I am using PyCharm 2020.1, and I am entering in all the fields in the settings like how ou say they should be, but it is never overwriting the icon in my IDE.

I am inputting the setting shown in the image below.

I am wondering if it's somehow being overrided by some other setting, or is there a specific format the icon file needs to be like?

I noticed some weird behavior when edits the boxes in the fields too. A lot of the times the icon file path, would randomly replace the pattern I enter, so I am curious to whether that could be a part of the problem.

Let me know if you'll need any other information for me. Thanks for the help.

![image](https://user-images.githubusercontent.com/17020909/83316837-5945e100-a1f6-11ea-87fc-5d4f78b597e4.png)

**Comment by mallowigi** [comment]
This is a brand new feature so of course there could still be bugs! 

To answer your second question, yes, once you press enter, it only shows the last part of the path you selected alongside the icon, but don't worry the path you entered is the one saved in the settings.

As for the first question, I suspect it is an issue of the same scale of the issue with PHP PSI Icons, e.g. that for icons usually replaced by third-party plugins like PHP or Python, there is some sort of order that applies and what you are seeing is actually the UI Icon, not the file icon. Tell me, is this issue happening with other extensions?

Thanks a lot!

**Comment by alexwolf22** [comment]
So I tried some more file types, .sh and .xml,  and getting the same results (see attached photo).

I did the test with an [svg](https://github.com/mallowigi/a-file-icon-idea/edit/master/src/main/resources/icons/xml/html_id.svg) image from this project, to make sure the file type wasn't the issue.

One thing I noticed was when I restarted PyCharm the icon flickered purple, like the test svg I used, for a Millisecond then went back to the plugin default. 

![Screen Shot 2020-05-30 at 7 17 47 PM](https://user-images.githubusercontent.com/17020909/83340843-ec405300-a2aa-11ea-9ca1-24e683d37c1b.png)

**Comment by mallowigi** [comment]
No no you didn’t write the right regexp haha. It should be `.*\.(xml)$`

**Comment by alexwolf22** [comment]
Ah okay I'm an idiot lol. I did the new pattern and it worked this time, even got some of the python logos to render.

Can you explain in a bit more detail how the regex matcher works and searches for files? I am familiar with regex, but still a bit confused about how it searches throughout the project directory tree with the match matter.

Also for the python image, it seems to work for opened files but not the ones in the sidebar.


![Screen Shot 2020-05-31 at 5 46 14 PM](https://user-images.githubusercontent.com/17020909/83363396-1bb49580-a367-11ea-8ef4-3486b70864fe.png)

**Comment by alexwolf22** [comment]
Also when I changed the color in the SVG image from grey -> bright orange, the grey folder color remained the same. I thought i could have been grey because the original SVG was grey as well.

![Screen Shot 2020-06-03 at 2 59 29 PM](https://user-images.githubusercontent.com/17020909/83678081-22cbe580-a5ab-11ea-9cca-77900d6d3775.png)

**Comment by bcnichols3** [comment]
Thanks for looking into this @mallowigi! My py project uses the common `test_.*\.py$` pattern and I've always been a little upset I don't see your pretty py test icon on my test files. But yeah looks like there's some bugginess in PyCharm in general.

**Comment by alexwolf22** [comment]
Yeah I remember one time when I was working last week, the icon did render properly, but later in the week, it went back to how it was in this post.

May try updating PyCharm. I think hey just made a new release.

**Comment by mallowigi** [comment]
The issue is because it conflcits with UI Icons imported from the Python package. You see, the custom associations works only for the project view and the tabs, all other instance of files uses the regular UI Icons provided by the package, that's why you often get this icon in commit panels, diff panels etc...

I started to refactor a bit to separate UI Icons for files from other UI Icons, in order to disable them altogether when disabling the File Icons feature, which was the cause of this issue and for PHP files as well, but I couldn't find why after disabling the feature the icons would simply disappear! And then my old computer crashed and I lost all my hard work.

It will take time until I'll get back in feet, so my apologies. You could still try your luck and fix it yourself though lol, that would be greatly appreciated :)

**Comment by smimon** [comment]
Also not working for me - trying to load a custom icon for C# files with the following:

![image](https://user-images.githubusercontent.com/2358820/89144393-d9325380-d577-11ea-9d5d-1973287c5b1d.png)

Once, quite by accident, the editor UI seemed to resolve the icon and apply it. Never been able to get it to work again, it just stays showing the path in the Icon column.

Also occasionally overwriting the Pattern column with the contents of the Icon column.

Cheers

**Comment by yackinn** [comment]
Try using a svg icon. It works for me.
