### ISSUE TITLE
Request: Instructions for Building

### ISSUE THREAD

**Issue by ciel** [mallowigi/a-file-icon-idea#9]
I absolutely love that you've made this - but I find myself wanting to extend it a bit and have no knowledge or experience with **gradle** - and have wasted quite a lot of time trying to figure it out. Is there any simple way to build a custom version of this repository with added associations for files or folders?

**Comment by mallowigi** [comment]
Follow the instructions on this page: http://www.material-theme.com/docs/development/installation/

**Comment by ciel** [comment]
Thank you!
