### ISSUE TITLE
Incorrect icons for some files

### ISSUE THREAD

**Issue by 5AbhishekSaxena** [mallowigi/a-file-icon-idea#92]
I am using the plugin in android studio, I have a kotlin project but is showing java icon in some kotlin files and some with kotlin icon.

**Comment by mallowigi** [comment]
screenshot?

**Comment by 5AbhishekSaxena** [comment]
Here: https://imgur.com/a/seKCv8D
As you can see I have all the kotlin files but the icon next to then is the one which is used by java.

**Comment by mallowigi** [comment]
This has been changed in the last versions. Unfortunately Android Studio is pretty slow to catch up with IntelliJ EAP releases, so unfortunately you will have to wait up until they catch up with 2020.2 EAP.
