### ISSUE TITLE
Custom Folder Association Not Working

### ISSUE THREAD

**Issue by mgroth0** [mallowigi/a-file-icon-idea#94]
<img width="1120" alt="Screen Shot 2020-06-15 at 11 18 26 AM" src="https://user-images.githubusercontent.com/12831489/84675218-f04eb080-aef9-11ea-954c-9e768107d086.png">

I've also tried just using the pattern `mlib` but this didn't work either

**Comment by mgroth0** [comment]
Actually, it worked! Took a few minutes for some reason. Perhaps an update could automatically refresh all icons when the new settings are applied or the preferences window is closed.

**Comment by mallowigi** [comment]
This is a known bug that I was supposed to release soon but unfortunately my computer broke and I lost all my work so I'm pretty bummed out and I don't know when I'll get back to my feet.

**Comment by mgroth0** [comment]
I'm sorry to hear that. Best wishes getting everything set up again.
