### ISSUE TITLE
Questions about the Chrome Extension

### ISSUE THREAD

**Issue by kidonng** [mallowigi/a-file-icon-idea#96]
- Will you open source the extension?
- The extension no longer works when **Repository refresh** preview feature is enabled.
![image](https://user-images.githubusercontent.com/44045911/84965452-87f21000-b141-11ea-8e2a-6f6439b4d1cb.png)
- It doesn't work with [Refined GitHub](https://github.com/sindresorhus/refined-github)'s `edit-files-faster` feature, but [can be fixed](https://github.com/sindresorhus/refined-github/issues/1993#issuecomment-487423210).

**Comment by mallowigi** [comment]
I also use refined github and didn’t had any issues with that...

Anyway it’s on my list of todo things but I am a bit busy at work so I can’t attend to it .

I don’t know about this refresh feature, is that something new?

**Comment by mallowigi** [comment]
Man, I never pushed my work?! Oh my gosh and I lost my computer... learnt my lesson...

**Comment by kidonng** [comment]
> I also use refined github and didn’t had any issues with that...

Sorry I didn't make it clear, it's Refined GitHub's [`edit-files-faster`](https://github.com/sindresorhus/refined-github/blob/master/source/features/edit-files-faster.tsx) feature. The function won't work after replacing the icon.

> I don’t know about this refresh feature, is that something new?

It's in public beta today:
![image](https://user-images.githubusercontent.com/44045911/84989761-bd652080-b176-11ea-9131-ee671d1efd8b.png)

> I never pushed my work?! Oh my gosh and I lost my computer...

That's too bad... But luckily it's a browser extension, so we still have something left.

**Comment by mallowigi** [comment]
Oww, I can say that I don't really like this UI...

I need to check in my older computer if by some chance the project is still there, otherwise I'd have to redo it from scratch which sucks...

**Comment by kidonng** [comment]
FYI, a similar extension fixed the issue with new design: homerchen19/github-file-icon#76

**Comment by mallowigi** [comment]
I have found the source code, albeit compiled, from the extension. I'll try to salvage as much as possible.

**Comment by mallowigi** [comment]
https://github.com/mallowigi/a-file-icon-web

I've managed to redo everything, and it works now without refined-github
